### ISSUE TITLE
thread dump using stackmob-5 (5.1.2) paper-354

### ISSUE THREAD

**Issue by mrcoffee1026** [Nathat23/StackMob-5#102]
getting this every few moments from the time the server starts up.
https://pastebin.com/wD5KqBF9

**Comment by Nathat23** [comment]
Try with this build of @Aurelien30000 pull request, https://drive.google.com/file/d/1mdQPA9MuZtZBJDjHfiO7lZZmd2qFsm9f/view?usp=sharing

**Comment by Aurelien30000** [comment]
How many entities does your world have ? I think it's caused when players join the server 🤔 Could you provide us the entire log ? :)

**Comment by mrcoffee1026** [comment]
this log was from when there were 4 or less players on... the entity count was not high at the time when anyone joined, there was griping of a lot of lag while the stack dump was showing up in the log.  
Full log: https://pastebin.com/JnTq7Mbf
I use this very old thing to try to count entities... stacked entities only count as 1 so there has not been a high entity count for any mobs since using this plugin... though I'm sure that will change now that i'm running for awhile without it.  I'll have to try the suggested build the next time I restart unless you have any other suggestions for other things to try first?  This seemed to start up kind of suddenly and fairly recently, I'd say within the last 2-3 paper builds.

**Comment by Aurelien30000** [comment]
Hum, weird, could you make a spark profiler during a freeze ? (with this plugin https://www.spigotmc.org/resources/spark.57242/) Thanks ! :)

**Comment by mrcoffee1026** [comment]
I tried with the new build version and got the same issue with the thread dumping... additional errors with it though don't know if that's at all helpful: https://pastebin.com/a2ub6b5K
And then when I restarted again with the mentioned plugin... it didn't happen again?  So I never got the opportunity to do the profiler thingie during a freeze since it didn't happen.  Most mysterious

**Comment by Aurelien30000** [comment]
Obsiously, too many entities spawn, I don't know why, but I never had this issue from all my huge tests. Even with thousands entities, sm spawnlistener doesn't exceed 25% of the server thread Check your spawns and plugins is this issue occurs during server starting 🤔

**Comment by Nathat23** [comment]
> Obsiously, too many entities spawn, I don't know why, but I never had this issue from all my huge tests. Even with thousands entities, sm spawnlistener doesn't exceed 25% of the server thread Check your spawns and plugins is this issue occurs during server starting thinking

I don't think this is anything to do with the amount of entities, the server seems to be hanging when iterating though the world's living entity list.

**Comment by Aurelien30000** [comment]
Might be only the getNearby, because "SpawnListener" doesn't iterate all the entities.

**Comment by Nathat23** [comment]
Asking about this on the Paper discord, the crashing appears to be slimefun. I'm guessing that the reason StackMob appears is just coincidence since the stack traces are taken at the same interval the stacking tasks run.
