### ISSUE TITLE
spawn reasons

### ISSUE THREAD

**Issue by HiddenOasisMC** [Nathat23/StackMob-5#105]
I can't seem to find a list of the proper "syntex" or typing of the spawn reasons. I am wanting to set it so that I can use the following to make it so natural spawns and spawn eggs still target players but mobs from spawners do not.

 If the entity's spawns reason is listed below, do not disable targeting
reason-blacklist: [ ]

Is there any chance to get at least a small list added to the commentary within the config that will help those of us who are newer to the plugin seen? If not, could I get a reply with the right way to type the 2 options I am looking for? If I can get this fixed this will have become the best mob stacking plugin on the market as we have tried literally all free and some paid versions of mob stackers, and this is the only one that works the way we need it to without messing up other plugins that we are running.

**Comment by Aurelien30000** [comment]
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html ^^

**Comment by Aurelien30000** [comment]
I will also add this link to the default config.

**Comment by HiddenOasisMC** [comment]
Omg you are awesome thank you very much :)

**Comment by HiddenOasisMC** [comment]
Could you tell me what i did wrong because now it is sort of working, some mobs go hostle and some dont but its not mob spacific, just random mobs that naturally spawn will target and the rest dont.


disable-targeting:
  enabled: true
   If the entity's type is listed below, do not disable targeting.
  type-blacklist: []
  type-blacklist-invert: false
   If the entity's spawns reason is listed below, do not disable targeting (**)
  reason-blacklist: [DEFAULT,NATURAL,EGG,SPAWNER_EGG]
  reason-blacklist-invert: false

**Comment by Aurelien30000** [comment]
That's a good question because I don't really know if this option uses spawn reasons or target reasons, I don't know neither what's expected :/

**Comment by Nathat23** [comment]
Its spawn reasons. There is currently an issue where the spawn reason of dead mobs does not get given to newly spawned mobs.
