### ISSUE TITLE
mcMMO swords / axes / unarmed not levelling properly with stacked mobs

### ISSUE THREAD

**Issue by RalphORama** [Nathat23/StackMob-5#111]
Players on my server are not receiving mcMMO experience from killing stacked mobs after killing the first mob in the stack.  When a player kills a naturally spawned mob or the first mob in a new stack of mobs, they receive experience for mcMMO combat skills (swords / axes / unarmed).  When a player kills subsequent mobs in the stack, they receive no mcMMO experience.

I have `hooks.mcmmo` set to `true` in my config file.

My config file: [https://pastebin.com/Pp9f4hLD](https://pastebin.com/Pp9f4hLD)

Server info:

- Version: Paper version git-Paper-90 (MC: 1.16.1) 
- StackMob version: 5.2.2
- mcMMO version: 2.1.133

**Comment by Nathat23** [comment]
hooks.mcmmo disables the mcmmo experience for stacked mobs. If you want stacked mobs to give experience this needs to be disabled, however experience won't be multiplied.

**Comment by RalphORama** [comment]
Ah, OK, thanks for clarifying. IMO, there should be an option in the config to enable mcMMO XP at reduced rates.  If I have time this weekend, I'll work on implementing that feature and open a pull request.
