### ISSUE TITLE
API is missing

### ISSUE THREAD

**Issue by Rocologo** [Nathat23/StackMob-5#112]
It seems that you have removed the API, which I was using ? 

https://github.com/Rocologo/MobHunting/issues/668

Kind regards
Rocologo

**Comment by Nathat23** [comment]
The EntityManager class is now in the entity package, https://github.com/Nathat23/StackMob-5/blob/master/src/main/java/uk/antiperson/stackmob/entity/EntityManager.java

**Comment by Rocologo** [comment]
Thank you.
