### ISSUE TITLE
Stacker doesn't work

### ISSUE THREAD

**Issue by qSeek** [Nathat23/StackMob-5#12]
After 1.15 Update stacker doesn't work.
Server Version: https://i.imgur.com/YMq3oNO.png
StackMob Version: https://i.imgur.com/Yl3knUV.png
Proof: https://i.imgur.com/YMq3oNO.png (Spawned using Spawn Egg)
Config: https://pastebin.com/zhX7yvp6

**Comment by Nathat23** [comment]
You have pasted the same image twice

On 4 Jan 2020 15:01, qSeek <notifications@github.com> wrote:

After 1.15 Update stacker doesn't work.
Server Version: https://i.imgur.com/YMq3oNO.png
StackMob Version: https://i.imgur.com/Yl3knUV.png
Proof: https://i.imgur.com/YMq3oNO.png (Spawned using Spawn Egg)
Config: https://pastebin.com/zhX7yvp6

**Comment by qSeek** [comment]
Server Version: https://i.imgur.com/K1SY1LV.png

**Comment by jere62smi** [comment]
Well I tested your latest version and I still can't stack mobs. On the other hand, if I kill mobs that are already stacked, the others will stack up to him if I put a mob next to him. Conversely, if I want to stack mobs together that have never been stacked, it doesn't work.

**Comment by N0tMyFaultOG** [comment]
Can confirm, mobs do not stack on 1.15.1 rn using version 5.0.1

**Comment by Nathat23** [comment]
Alright, since I don't really know the cause of the problem since there could be various reasons, I have created a special version which gives debug information about a specific entity. This can be found at: https://drive.google.com/file/d/1MetFx2OFihwUeVNJYMidMe-nCRkLlYhY/view?usp=sharing

To create this info, you will have to use the stacking tool and change it to the 'DEBUG' mode. Then right click an entity that isn't stacking. You should now see messages in the console. Wait for a while, then pastebin the output and link it here.

**Comment by N0tMyFaultOG** [comment]
In case I did it correctly, it returned `[StackMob] Now tracking entity cb0a3100-1e35-4fbc-9057-a5b3004c00b9` only, nothing else.
I waited apx. 10 minutes, hopefully that was long enough.

**Comment by Nathat23** [comment]
> In case I did it correctly, it returned `[StackMob] Now tracking entity cb0a3100-1e35-4fbc-9057-a5b3004c00b9` only, nothing else.
> I waited apx. 10 minutes, hopefully that was long enough.

just making sure, you have spawned at least 5 mobs in the same area?

**Comment by N0tMyFaultOG** [comment]
> > In case I did it correctly, it returned `[StackMob] Now tracking entity cb0a3100-1e35-4fbc-9057-a5b3004c00b9` only, nothing else.
> > I waited apx. 10 minutes, hopefully that was long enough.
> 
> just making sure, you have spawned at least 5 mobs in the same area?

Yeah

**Comment by Nathat23** [comment]
So at the moment their doesn't seem to be a problem with stackmob, but with the server software. Since sometimes the entity you right click is never iterated over at all.

**Comment by Nathat23** [comment]
> So at the moment their doesn't seem to be a problem with stackmob, but with the server software. Since sometimes the entity you right click is never iterated over at all.

Yeah its not a bukkit problem. 


> > > In case I did it correctly, it returned `[StackMob] Now tracking entity cb0a3100-1e35-4fbc-9057-a5b3004c00b9` only, nothing else.
> > > I waited apx. 10 minutes, hopefully that was long enough.
> > 
> > 
> > just making sure, you have spawned at least 5 mobs in the same area?
> 
> Yeah

does restarting fix it?

**Comment by Nathat23** [comment]
This took me wayyy too long to notice...https://github.com/Nathat23/StackMob-5/commit/d1ef85f1d6c4da64792aca8e2e7995f80f8042e7
