### ISSUE TITLE
Not stacking natural mobs?

### ISSUE THREAD

**Issue by Chippy577** [Nathat23/StackMob-5#120]
So im on my server and there are insane spawn rates, stackmob is working with mobs spawned with spawners and spawn eggs but not natural spawning mobs, is there anything in the config that I can mess with to fix that?

**Comment by Nathat23** [comment]
This can be changed in the reasons-blacklist list in the config file. However I would advice against this, as this will negatively impact performance as more mobs will be spawned by the server in order to fill the mob caps.

**Comment by Chippy577** [comment]
What do I change the reasons-blacklist to, do I delete the NATURAL or replace it or what do I do?

**Comment by Nathat23** [comment]
> What do I change the reasons-blacklist to, do I delete the NATURAL or replace it or what do I do?

remove natutal

**Comment by Chippy577** [comment]
ok thanks
