### ISSUE TITLE
Stacking Mobs even with custom names

### ISSUE THREAD

**Issue by PancakeCatsss** [Nathat23/StackMob-5#128]
I know you can right-click a stack with a nametag and that will unstack one mob from the stack giving it a name, however, we have custom bosses on the server and these bosses spawn mobs with custom names and it still stacks them. Any way to fix this?

**Comment by Nathat23** [comment]
What plugin are you using for the bosses?

**Comment by PancakeCatsss** [comment]
It is a custom made plugin by me, using Entity.setCustomName(""); does not prevent them from being stacked.

**Comment by Nathat23** [comment]
You will need to create your own plugin hook, example https://github.com/Nathat23/StackMob-5/blob/master/src/main/java/uk/antiperson/stackmob/hook/hooks/CitizensHook.java or listen to the StackMergeEvent and cancel it.

**Comment by PancakeCatsss** [comment]
Perfect, Thank you.
