### ISSUE TITLE
Some lag with StackMob 5.3.2

### ISSUE THREAD

**Issue by Florianpal1** [Nathat23/StackMob-5#129]
Hello, in version 5.3.2 of StackMob i have some micro lag.
I use paper-195 in 1.16.3.

Timings in 5.2.3:
![unknown](https://user-images.githubusercontent.com/36370356/93015930-b60ab300-f5bd-11ea-99a0-17a13211050c.png)
Timings in 5.3.2:
![unknown](https://user-images.githubusercontent.com/36370356/93015941-ccb10a00-f5bd-11ea-8760-0310c2e788ac.png)

**Comment by Nathat23** [comment]
Can you provide the full timings report?

**Comment by Nathat23** [comment]
Also the output of '/sm stats' when first starting and after a few mins?

**Comment by Florianpal1** [comment]
Full timings : https://timings.aikar.co/?id=cafa3d79431f48859fe777a84d262c73

I have downgrade to StackMob 5.2.3.

**Comment by Nathat23** [comment]
Is there anything specific that causes this?

**Comment by Florianpal1** [comment]
Not really, I haven't do any change between 5.2.3 and 5.3.2

**Comment by Nathat23** [comment]
Do you have any plugins that remove entities?

**Comment by Florianpal1** [comment]
No but i have saml, it freeze entities.

**Comment by Nathat23** [comment]
try again without saml, it might be doing weird things.

**Comment by Florianpal1** [comment]
actually, i can't restart my server. My players are a little fed up.

**Comment by Florianpal1** [comment]
![image](https://user-images.githubusercontent.com/36370356/93901404-c7a73580-fcf6-11ea-9c1f-200860ce9037.png)
Same problem with 5.3.4.

**Comment by Nathat23** [comment]
> ![image](https://user-images.githubusercontent.com/36370356/93901404-c7a73580-fcf6-11ea-9c1f-200860ce9037.png)
> Same problem with 5.3.4.

Are you using latest paper?

**Comment by Florianpal1** [comment]
I use paper-199

Téléchargez Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by satyrnhub** [comment]
use latest paper
or yatopia
