### ISSUE TITLE
Sometimes Stacking and error Message in log

### ISSUE THREAD

**Issue by Hadusch** [Nathat23/StackMob-5#13]
Helloy i think everything is set up properly this is my cfg(https://pastebin.com/apkXQBnG) but the cows sometimes seem to stack and other times not and i get this error Spamed https://pastebin.com/d14D5ZkR im using the newest version of the plugin from spigot and paper#33 1.15.1 ty

**Comment by Nathat23** [comment]
For the stacking issues, see #12
