### ISSUE TITLE
StackMob 5.3.3 scoring high on aikar timings

### ISSUE THREAD

**Issue by cloakfox** [Nathat23/StackMob-5#131]
Just wanted to share this so that the plugin author can maybe make even more performance improvements to this plugin.

https://imgur.com/a/VSnVRvd

**Comment by Nathat23** [comment]
whats the output of '/sm stats'?

**Comment by Nathat23** [comment]
also can you provide the link rather than a screenshot?

**Comment by cloakfox** [comment]
> whats the output of '/sm stats'?



> also can you provide the link rather than a screenshot?

Output of /sm stats: https://imgur.com/a/hQ5hIYr

Link to timings report: https://timings.aikar.co/?id=19c126c6c2474ce09762c7fbad9d4a7e

**Comment by Nathat23** [comment]
Did you upgrade from a previous version and so has performance gotten worse?

**Comment by cloakfox** [comment]
> Did you upgrade from a previous version and so has performance gotten worse?

I upgraded from 5.3.1, performance has gotten better, im just sharing the fact that it's still scoring high on the aikar timings.

**Comment by Nathat23** [comment]
> > Did you upgrade from a previous version and so has performance gotten worse?
> 
> I upgraded from 5.3.1, performance has gotten better, im just sharing the fact that it's still scoring high on the aikar timings.

Did you use a version previous to 5.3.1?

Anyways, would you be able to run a spark profile, https://www.spigotmc.org/resources/spark.57242/

**Comment by cloakfox** [comment]
> > > Did you upgrade from a previous version and so has performance gotten worse?
> > 
> > 
> > I upgraded from 5.3.1, performance has gotten better, im just sharing the fact that it's still scoring high on the aikar timings.
> 
> Did you use a version previous to 5.3.1?
> 
> Anyways, would you be able to run a spark profile, https://www.spigotmc.org/resources/spark.57242/

I most likely also used older versions then 5.3.1 not sure exactly which ones i've used though.

Spark sampler: https://spark.lucko.me/#0qCzUKoapS

Extra timings: https://timings.aikar.co/?id=e76d6b9cd21a4729a1bbc8f63f86d472

**Comment by Aurelien30000** [comment]
@cloakfox please try this https://github.com/Aurelien30000/StackMob-5/actions/runs/257837303

**Comment by cloakfox** [comment]
> @cloakfox please try this https://github.com/Aurelien30000/StackMob-5/actions/runs/257837303

Thanks, will report tomorrow how this jar is performing! (Dont want to reboot any servers right now)

**Comment by cloakfox** [comment]
Noticed an error in console pop up with the jar you provided yesterday
https://pastebin.com/NeBR7Bxz

I will be able to get new timings & spark later today when a decent amount of players are online

**Comment by Aurelien30000** [comment]
> Noticed an error in console pop up with the jar you provided yesterday
> https://pastebin.com/NeBR7Bxz
> 
> I will be able to get new timings & spark later today when a decent amount of players are online
> 
> EDIT: https://timings.aikar.co/?id=bcb5cedaa4b04d4ead453b17a95a1fb0
> 
> No where to be found! Great succes?

Nice!

**Comment by Aurelien30000** [comment]
Error in console was also fixed -> https://github.com/Aurelien30000/StackMob-5/actions/runs/259668597
