### ISSUE TITLE
[Suggestion] Avoid deleting items that mobs equip prior to stacking

### ISSUE THREAD

**Issue by Tencryn** [Nathat23/StackMob-5#134]
As discussed on Discord, mobs that equip items after spawning lose them when they stack. This should be tweaked.

Firstly, mobs that spawn WITH armor are not important. Their item's can be ignored as is currently the case. As for mobs that equip items after spawning (such as when a player dies), a config option should be added to control what happens to the items should the mob stack.

You could implement the following 3 options: `Ignore items`, `drop items on stack`, or `do not stack`.

The default option should be to ignore items so that it matches current behavior, and admins can change that to one of the other two should they see fit.

**Comment by Nathat23** [comment]
I feel like having an option to stop stacking when equipped could be abused by players?

**Comment by Tencryn** [comment]
> I feel like having an option to stop stacking when equipped could be abused by players?

It could be, yes. However, you also have the option to prevent stacking of mobs that are nametagged. In the grand scheme of things, they're not that different. Both can be a abused on a public server, but less likely on a private server with friends and what not. A mob limiter could also be used to prevent mob item pick up after a set limit, should there be support for such. It's situational.

My preference however is option 2. Players don't lose their items so easily, and there wouldn't be a build up of mobs.

**Comment by Nathat23** [comment]
Yeah, I guess it's up to the server owner to decide how they want things to work since every server is different.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
