### ISSUE TITLE
java.lang.UnsupportedOperationException: wait-to-stack.reasons-whitelist list is null!

### ISSUE THREAD

**Issue by MrRayhonda** [Nathat23/StackMob-5#14]
**Describe the bug**
Updated from a 4.x version got the bridge, bridge didn't work. Deleted stack mob and bridge and generated files, downloaded latest version 5.x generated files Whitelisted Pig sheep chicken rabbit cow, not stacking. old stacks are still stacked but no mobs will stack. Ver 1.15.1

**To Reproduce**
take sheep egg, spam sheep.

**Expected behavior**
the sheep turn in to a stack of sheep separated by age and color.

**Screenshots/Videos**
https://i.ibb.co/JKPnKvs/2020-01-05-01-10-04.png

**Bukkit/Spigot AND StackMob version:**
Paper 1.15.1 Build#33
StackMob ver 5.0.1

**Additional context**
I think that's about it. I'm completely lost.

**Comment by Nathat23** [comment]
Did you previously use a beta version?

**Comment by MrRayhonda** [comment]
hmm not that i know of. I was using the public 4.x builds. Don't think i ever seen a beta for it. Even so, I deleted everything about stack mob and added the 5.0.1 to start fresh and this is happening. o,o I hope it can be fixed ^^

**Comment by MrRayhonda** [comment]
any news? I wonder if im the only one experiencing this. Still hoping for the best tho :D

**Comment by MrRayhonda** [comment]
Stackmob is spamming the console hard now https://pastebin.com/7wKeDVPk

**Comment by Nathat23** [comment]
can you provide your config file so i can reproduce?

**Comment by MrRayhonda** [comment]
yes absolutely here ya go
https://pastebin.com/5MaxvDrC

**Comment by Nathat23** [comment]
Add [] to the end of the reasons-whitelist line, should fix this.

**Comment by MrRayhonda** [comment]
like this?   reasons-whitelist: []

**Comment by Nathat23** [comment]
Yes

**Comment by MrRayhonda** [comment]
okay thank you :D I'll keep you posted if anything ^^

**Comment by MrRayhonda** [comment]
i did what u said and getting this
WARN 17:59:56
[StackMob]: Task #177 for StackMob v5.0.2 generated an exception
Console 17:59:56
java.lang.NullPointerException: null
at uk.antiperson.stackmob.tasks.MergeTask.run(MergeTask.java:37) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-33]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.1.jar:git-Paper-33]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1179) ~[patched_1.15.1.jar:git-Paper-33]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-33]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-33]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-33]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]



here is how i have the whitelist part of the config
wait-to-stack:
  enabled: true
  # For (x) times the stack task fires after spawn, don't stack this entity.
  wait-time: 5
  # Entity types that this should work for.
  types-whitelist: 
    - COW
    - CHICKEN
    - PIG
    - SHEEP
    - RABBIT
  types-whitelist-invert: false
  # Spawn reasons that this should work for.
  reasons-whitelist: []
    - SPAWNER
  reasons-whitelist-invert: false

**Comment by MrRayhonda** [comment]
got rid or - SPAWNER and it seems to be working now :O

**Comment by MrRayhonda** [comment]
ah crud... It's stacking mobs not on the whitelist :/ I just tested it with creepers
