### ISSUE TITLE
Bees do disappear

### ISSUE THREAD

**Issue by Hadusch** [Nathat23/StackMob-5#140]
On my Server the Bees disapear i dont know on which process but in 1 day Cycle there are allready many missing 

latest reproduced on
Paper 1.16.3 204 and Stackmob 5.3.5

attached are the config and a screenshot of the setup when i put them in a 1x1 space so they cant move much arround with 4 bee hives pointing on the block they behave as expected and dont disappear

i hope it can be fixed :) thank you for the great work

edit had to change the cfg to txt format normaly its in yml

![2020-09-03_08 50 43](https://user-images.githubusercontent.com/59511720/93975110-2ad8ac80-fd77-11ea-96d4-917821d1a04b.png)
[config.txt](https://github.com/Nathat23/StackMob-5/files/5266033/config.txt)

**Comment by Nathat23** [comment]
Is this like a standard design or something that I can replicate?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Hadusch** [comment]
well its basically just behives on the sides and a 3 wide gap in the middle the rest is just the dispensers and so on to farm the honey so it should not really do anything or might it even be a problem when dispensers interact with the hives when there are bees inside?

**Comment by Aurelien30000** [comment]
I probably found the cause of this after weeks of investigation... It may be caused by some inconsistencies in the merge tasks, more presicely with "matches" Set in the code. I'll try to figure it out and I'll open a merge request later :)
