### ISSUE TITLE
Dupe bug with sheep.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#143]
To reproduce, hold shears in off hand, and hold any other item in main hand (such as a piece of dirt.)
Right click stacked sheep with the piece of of dirt, the following error occurs, and sheep dupe the wool.
Error: https://pastebin.com/raw/1hRdCG7V
Our config: https://pastebin.com/raw/WKp6DRxB
Use Paper 1.15.2: Build 387: https://papermc.io/downloads#Paper-1.15
StackMob built upon latest commit: https://github.com/Nathat23/StackMob-5/commit/a89c8eada3e7e1db28088c18000cc8bc70eb3640

**Comment by Nathat23** [comment]
Fixed in above commit.
