### ISSUE TITLE
Does odd things to invisible armor stands (breaking Slimefun functionality)

### ISSUE THREAD

**Issue by mrcoffee1026** [Nathat23/StackMob-5#15]
Slimefun uses a number of "player_head" items which when placed also create an invisible armor_stand with a title to display additional information.  While StackMob is installed, it replaces the displayed text with the text "Armor Stand", and continues to generate an infinite amount of invisible armor stands in the same block position.  I can kill invisible armor stands with commands but regular players cannot do this and there would be a LOT of them to kill in the location if the block was placed for very long.

I tried adding "armor_stand" to the stacking blacklist though this had no effect.

StackMob >> StackMob version 5.0.1
[17:54:11 INFO]: Paper v1_15_R1
[17:54:11 INFO]:
[17:54:11 INFO]: CS-CoreLib vDEV - 80 (git e3242c60)
[17:54:11 INFO]: Slimefun vDEV - 393 (git 9ff093af)

video demonstrating issue:
https://youtu.be/B55oUW4dPS8

**Comment by Nathat23** [comment]
Fixed in above.
