### ISSUE TITLE
[Feature Request] Limit the breeding 

### ISSUE THREAD

**Issue by arturek1666** [Nathat23/StackMob-5#155]
Please add breeding limiter so you can set how many can be breeded and a cooldown, so if there is stack of 100 cows after bread there is 50 they getting bigger so really quick you can just have unlimited food, with isn't good 

So like breed-cooldown 200
Max-breeding:5

**Comment by Nathat23** [comment]
I don't think a cool down is possible but a hard limit is?

**Comment by arturek1666** [comment]
Well if breeding it self has limit why the plugin removes that, If it does it should bring it back!!!

**Comment by Nathat23** [comment]
Breeding has a cooldown so that after breeding their is a time period where you cannot breed. I believe the plugin does respect this, but I won't be able to test until later today.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by arturek1666** [comment]
For some reason it doesn't respect it.. That's why i requested this feature.

**Comment by Nathat23** [comment]
Is this with breed event mode MULTIPLY or SPLIT?

**Comment by arturek1666** [comment]
MULTIPLY.

**Comment by Nathat23** [comment]
From my testing there is still the default minecraft cooldown for breeding. I can add a kid limiter though.

**Comment by arturek1666** [comment]
There is also an issue that if I have:
  breed:
    enabled: true
    # MULTIPLY - spawn as many baby entities possible providing there is enough food fed.
    # SPLIT - slice off an entity to that it can be bred normally.
    mode: SPLIT

and 
traits:
  sheep-color: true
  sheep-sheared: true
  slime-size: true
  horse-color: true
  llama-color: true
  parrot-variant: true
  drowned-hand-item: true
  age: true
  breed-mode: true
  love-mode: true
  cat-type: true
  mooshroom-variant: true
  fox-type: true
  bee-nectar: true
  bee-stung: true
  zoglin-baby: true
  piglin-baby: true
  leashed: true

they still merge with the mobs that are breed able.

**Comment by Nathat23** [comment]
A feature to limit the amount of mobs bred was added, if there are other issues make a new ticket.
