### ISSUE TITLE
Could not pass event EntityDeathEvent to StackMob v5.3.7

### ISSUE THREAD

**Issue by cloakfox** [Nathat23/StackMob-5#156]
https://pastebin.com/mU1G85eF

Saw this error in console on Paper 1.16.4

**Comment by Nathat23** [comment]
Does this occur when a player dies to a kingdomsx mob?

**Comment by cloakfox** [comment]
> Does this occur when a player dies to a kingdomsx mob?

Most likely, I don't use any other plugins that alter mob health
