### ISSUE TITLE
Stacked Mobs survive in the Void

### ISSUE THREAD

**Issue by TehAwesomestKitteh** [Nathat23/StackMob-5#157]
**Context:** I did a stress test for my server to see how many mobs it can handle by having spawners spawn a ton of mobs in one chunk. The result was over 100+ stacked (100x stack) mobs. Current config settings are set so that only one dies at a time. To speed up clean-up, instead of killing them all one-by one (see: 100+, 100x stacks), I just sent them all to the void below

**Assumption:** They would all die immediately since nothing comes back from the void anyways

**Result:** It's been 5 minutes and I can still see them, zooming in tells that they are, indeed, dying one by one. They are now stuck in a purgatory until the last of their respective stack dies off

**Comment by Nathat23** [comment]
This can be fixed in the config by adding VOID to the reasons list for the SINGLE death option. You would also need to change the priority of the 'ALL' death option to one above that of SINGLE.

**Comment by TehAwesomestKitteh** [comment]
That worked, thanks
