### ISSUE TITLE
Console Error Spamming

### ISSUE THREAD

**Issue by oldmc** [Nathat23/StackMob-5#16]
![Capture](https://user-images.githubusercontent.com/59742626/72172814-ba7e2c80-339b-11ea-852e-80f0262ad463.PNG)

**Comment by Nathat23** [comment]
well the problem here is that stackmob 5 only supports 1.15, but you can change the 'visibility' setting in the config to the other options and this should go away.

**Comment by oldmc** [comment]
Thank you for your response
