### ISSUE TITLE
Error while disabling stackmob.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#162]
We get this on nearly every shutdown.
https://pastebin.com/raw/RYN6ygCp

Using latest compiled on https://github.com/Nathat23/StackMob-5/commit/b1492176e545a61ebe3c0945455f88619dcb2ff7
Paper 1.16.4 Build 332

**Comment by Nathat23** [comment]
How long has this been occurring for?

**Comment by andrewkm** [comment]
Probably months...
I just could never be asses to report it as I've always been so swamped during my shutdowns, but finally today was like ehhhhh alright time to GitHub this.

**Comment by Nathat23** [comment]
Are you using any plugins that load/unload worlds?

**Comment by andrewkm** [comment]
Not necessarily, unless Multiverse counts?
