### ISSUE TITLE
Thread dump triggered by stackmob?

### ISSUE THREAD

**Issue by mrcoffee1026** [Nathat23/StackMob-5#164]
Had very laggy thread dump, restarted and within a few moments had another one.  Stackmob is the first thing coming up in the dump... restarting with it disabled seems to have resolved the issue for now.  This might be due to recent paper updates as I haven't changed any plugin configuration.

StackMob-5.4.0
[14:54:19 INFO]: This server is running Paper version git-Paper-353 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[14:54:19 INFO]: Checking version, please wait...
[14:54:19 INFO]: Previous version: git-Paper-350 (MC: 1.16.4)

Thread Dump:
https://pastebin.com/aRYHkyUV

**Comment by Nathat23** [comment]
Do you know if there's anything that causes it?

**Comment by mrcoffee1026** [comment]
maybe just lots of stacks?  After the first one, it happened pretty quickly while i was near a rather efficient enderman farm, so there certainly were many stacking endermen going on.

**Comment by mrcoffee1026** [comment]
i haven't seen this happen again so i guess it's a non issue.
