### ISSUE TITLE
Max stack disappears constantly.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#165]
When you have a max stack in the high numbers, with another stack nearby, it disappears sometimes for no reason.
I understand this is a stupidly vague description, so I've made a video below to demonstrate the issue.

**StackMob compiled on**: https://github.com/Nathat23/StackMob-5/commit/d49602644363544a8c7ebc2e992adb75cddb0a30
**Server**: Paper 1.16.4 Build 366
**Config**: https://pastebin.com/qAcs726U
**Video**: https://youtu.be/M9YqkHMrAEU

**Default config testing**: https://pastebin.com/Zy9CsfYP
**Video**: https://youtu.be/eEIGNfjPxpI
In this video we can examine some weird behavior however the bug is not reproduced.
The weird behaviour is the 30 (max) stack when killed off one by one, continues to grab pigs from the non max stack.

Continued testing:
**Only config alterations are:**
```
stack:
  max-size: 500
  merge-range: [12,12,12]
  threshold:
    amount: 1
```
**Video**: https://youtu.be/sPPQgH8RtTw
Here we once again see the 500 stack disappear.

**BUG FOUND**:
Ok it looks like with my original config in my original test, if I simply make the threshold 4 or above, the bug is completely gone.
A threshold of 1, 2 or 3 causes this bug to happen and causes max stacks to disappear. For now I will set my threshold to 5, however it would be nice if 1, 2 and 3 functioned correctly. :)

**Comment by Nathat23** [comment]
Should be fixed.

**Comment by andrewkm** [comment]
Confirmed fix.
