### ISSUE TITLE
Could not pass event ChunkUnloadEvent

### ISSUE THREAD

**Issue by tnht** [Nathat23/StackMob-5#168]
Error: Could not pass event ChunkUnloadEvent to StackMob

https://www.dropbox.com/s/50kii2xx0kpcu8p/Zrzut%20ekranu%202021-01-11%20o%2012.32.38.png?dl=0

**Comment by Nathat23** [comment]
Do you know what causes this?

**Comment by tnht** [comment]
Probably nothing. But the error looks terrible.

**Comment by Aurelien30000** [comment]
Dn't use spigot, migrate to paper :)
