### ISSUE TITLE
Stacking is not working with an enabled threshold over 1.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#17]
Hello again @Nathat23 I have returned to play with the latest on 1.15.1
First bug I found is threshold. Any activated threshold over 1 breaks stacking.

Version: 5.0.1 (From https://spigotmc.org, I'm not yet using development builds)
Config: https://pastebin.com/4zzgfbix

The following = stacking works.
```
  threshold:
    enabled: true
    amount: 1
```
The following = stacking does NOT work.
```
  threshold:
    enabled: true
    amount: 2
```
The following = stacking does NOT work.
```
  threshold:
    enabled: true
    amount: 3
```
The following = stacking works.
```
  threshold:
    enabled: false
    amount: 3
```

**Comment by andrewkm** [comment]
PS: I've added this here for those who would like to test development builds.
It is on a 3 hour poll interval.
https://ci.ecocitycraft.com/job/StackMob-5/

**Comment by Nathat23** [comment]
This also might be because the server wasn't restarted between config changes?

**Comment by andrewkm** [comment]
No, this issue’s config was done on a server startup.

I have just tested again to be absolutely sure.

Definitely a bug :)

**Comment by Nathat23** [comment]
Is this still the case? I can't seem to replicate.

**Comment by andrewkm** [comment]
This is no longer an issue.
I'm not exactly sure what went wrong and if/where it was fixed (perhaps a setting confliction), but after testing the latest version, it seems to be fixed.
