### ISSUE TITLE
What are the ID's for disabling certain entity stacks?

### ISSUE THREAD

**Issue by MonkeyDumplings** [Nathat23/StackMob-5#174]
Don't want to ruin farms and we want to disable dogs, piglins, zombie pigmen, creepers and villagers.
I don't know the all caps ID's for those?
Do i do it like this:
types-blacklist: [VILLAGER]
types-blacklist: [CREEPER]

Or like this:
types-blacklist: [VILLAGER, CREEPER, etc.]

**Comment by Nathat23** [comment]
like the second one.

**Comment by MonkeyDumplings** [comment]
Thank you
