### ISSUE TITLE
"Health must be between 0 and 12.0" Console Error

### ISSUE THREAD

**Issue by sebastiantho** [Nathat23/StackMob-5#179]
Getting this console error:
https://pastebin.com/gyLW6HdQ

Here's my config:
https://pastebin.com/ZaBx9v6h

**Comment by sebastiantho** [comment]
I updated to the newest version. It is no longer an error but instead a warning. Same message tho.

**Comment by Nathat23** [comment]
do you know what causes it?

**Comment by Aurelien30000** [comment]
Known for a while :/ You can ignore them, but if you have any info about how to reproduce them, tell us 😅

**Comment by Nathat23** [comment]
Duplicate of #26
