### ISSUE TITLE
breed.enabled.false = doesn't stop breeding.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#18]
Version: 5.0.1 (From https://spigotmc.org, I'm not yet using development builds)
Config: https://pastebin.com/4zzgfbix

Basically, make a stack of 6 chicken.
Right click the chickens with seeds, you then get 3 baby chickens and the 6 chickens remain stacked.
I'd like to completely disabled breeding. How can I do this?

**Comment by Nathat23** [comment]
Did you fully restart the server after making that changing that in the config?

**Comment by andrewkm** [comment]
You are correct, this needed a full restart, not just an /sm reload.
