### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jravuwannab** [Nathat23/StackMob-5#181]
Is it possible to make an entire stack die from fall damage? We have an issue where if there is a stack of mobs and they take enough fall damage for one to die, only one dies. We need it where they all die. Is this possible? If it isn't, it'd be a nice feature nonetheless.

**Comment by Nathat23** [comment]
you could go to the death section in config and set the priority of ALL to 0, add FALL to reason-blacklist and enable reason-blacklist-invert?
