### ISSUE TITLE
Pregnant turtles trait

### ISSUE THREAD

**Issue by HauserGrim** [Nathat23/StackMob-5#187]
I fixed this for myself a long time ago.
The problem is that only Paper has this method, but I decided to show it anyway.

https://github.com/HauserGrim/StackMob-5/blob/master/src/main/java/uk/antiperson/stackmob/entity/traits/trait/TurtleHasEgg.java
Use it or not use it however you want.

**Comment by Aurelien30000** [comment]
Nice! You should make a pr to share your work to all users ;)
Unavailability on spigot doesn't really matter, open ``TraitManager.java`` and add an obvious check _(example below)_ to ignore Turtle egg trait on this server software:

![image](https://user-images.githubusercontent.com/43724816/107936375-de3e7980-6f82-11eb-826d-c5e7fc8c91fe.png)

Thanks!

**Comment by HauserGrim** [comment]
https://github.com/Nathat23/StackMob-5/pull/188
