### ISSUE TITLE
How do i use the config

### ISSUE THREAD

**Issue by Silmoheru** [Nathat23/StackMob-5#191]
how would i go about adding another mob to the blacklist

# Names of worlds where there should be no stacking
worlds-blacklist: []
worlds-blacklist-invert: false
# Types of entity which should not stack (3)
types-blacklist: [VILLAGER]             <----------- do i just put it like this [VILLAGER,BEE] OR 
                                                                                                                               [VILLAGER],[BEE] OR 
                                                                                                                               [(VILLAGER),(BEE)]
types-blacklist-invert: false
# If the entity's spawn reason is listed below, do not stack. (2)
reason-blacklist:
  - SHOULDER_ENTITY
  - NATURAL
reason-blacklist-invert: false

**Comment by Nathat23** [comment]
yes a comma

**Comment by Silmoheru** [comment]
just a comma ok thank you
