### ISSUE TITLE
All mobs stacking even though I have a whitelist.

### ISSUE THREAD

**Issue by MrRayhonda** [Nathat23/StackMob-5#20]
Finally got stackmobs working thanks to you but now for some reason even though i have a white list for Pig,Cow,Sheep,Chicken and rabbits only, all mobs still stack.

Config: https://pastebin.com/SVb3Ygx4

I only want my whitelisted mobs to stack for the server and im not sure why this is happening. I've tried multiple spacing methods for the list section as well, none have worked.

Hopefully this will be my last issue and I will be able to stop pestering you haha

**Comment by Nathat23** [comment]
Add the mobs to the list called "types-blacklist" and then enable the option below called "types-blacklist-invert".

**Comment by MrRayhonda** [comment]
ouuu that worked!!! Thank you so much :) Sorry again for bugging you. Glad to finally have this amazing plugin working again!
