### ISSUE TITLE
Mobs not acting as stacked mobs after some amount of time.

### ISSUE THREAD

**Issue by TraceLosu** [Nathat23/StackMob-5#202]
After updating the plugin from 5.5.0 to 5.5.2 by restarting the server and replacing the .JAR file, the plugin seems to not work on stacked mobs. Stacked mobs now act as normal mobs after some amount of time of them spawning. We've tried spawning and despawning, we've tried restacking. All of this did not work.

Using git-Tuinity-"7734ef0" and StackMob 5.5.2. No errors were found in console.

**Comment by TraceLosu** [comment]
Closed the issue, did not see the update.

**Comment by Nathat23** [comment]
Just to confirm, updating fixes the issue?

**Comment by TraceLosu** [comment]
> Just to confirm, updating fixes the issue?

Yes, the plugin ran as expected.
