### ISSUE TITLE
Natural Spawns Denied

### ISSUE THREAD

**Issue by KolakZ** [Nathat23/StackMob-5#206]
For some reason, Mob Stack doesn't work with naturally spawned entities. It only works with entities spawned using an egg.

**Comment by Nathat23** [comment]
This is how it is configured by default and it is intentional. Stacking natural mobs like fish only means more will spawn, creating more load on the server. If you really want to stack natural mobs you can remove 'NATURAL' from 'reasons-blacklist'.
