### ISSUE TITLE
Mobs stacking to newest mob, not to those already stacked.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#21]
Version 5.0.2
Build 4: https://ci.ecocitycraft.com/job/StackMob-5/changes
Current Config: https://pastebin.com/Sk9LTwpj

Just got the following report:
https://ecocitycraft.com/forum/threads/mob-stacking.193839/

Seems it is indeed an issue.
Posted below:

**Brief Description:**
Mobs stack to the newest mob spawned and not the already stacked group
**Instructions:**
Go to a mob spawner
Look at how they stack
**How many times did you recreate this?:**
Many times
**Result:**
The already stacked mobs are stacking to the new mob spawned from the mob spawner, which results to mobs getting tp'ed around a lot
**Expected Result:**
The new mob spawned from a mobspawner would go into the already stacked mob group, so they don't tp around all the time

Video: https://imgur.com/a/I8vrjYe#mROBNtQ
Please let me know how we can have mobs spawn into the stack already made as opposed to that stack getting TPed around. (Seems that Ghasts are not affected by this).

**Comment by Nathat23** [comment]
You could try increasing 'wait-time' under 'wait-to-stack' to like 10 or something and see if that improves it.

**Comment by andrewkm** [comment]
That doesn't help, eventually the stack TPs away to the newly spawned mob.
Is it possible you could make it so new mobs go into stacks as opposed to the stacks going into the new mobs.

**Comment by Nathat23** [comment]
Fixed in the above commit.

**Comment by andrewkm** [comment]
Confirmed fixed :)
