### ISSUE TITLE
Trying to change the config file failing

### ISSUE THREAD

**Issue by Rodaasboyy** [Nathat23/StackMob-5#212]
While trying to change the config file on an apexhosting server hosted on paper server. when i try to /sm reload it just ressets the config file and doesn't change the setting for the plugin.
Am I doing something wrong or is this an actual bug?

**Comment by Nathat23** [comment]
so what are you trying to change?

**Comment by Rodaasboyy** [comment]
For isntance the max stack to 100
Natural mobs not to stack
Stack update to 30 ticks
Stuff like that that i feel fits the server the best

**Comment by Nathat23** [comment]
Are you using an online editor? It may be better to download the config using FTP, modifying the config and then reuploading it.
