### ISSUE TITLE
Drop counts are wrong when killed in lava

### ISSUE THREAD

**Issue by madmagic007** [Nathat23/StackMob-5#213]
title, Stacked mobs dont drop the amount they should. example: 60 iron golems killed by lava only dropped 6 iron. when killed with a weapon by player they drop the correct amount.  Even when fire is the cause of death they drop the correct amount.
Without this plugin they always drop the correct amount and the items dont drop in the lava. it could be that thius plugin causes them to drop in the lava?
the lava is a single block high, 2 blocks above the ground, vainilla minecraft and before this plugin, item counts were always correct.

edit: it seems to be the drops of a single mob most of the time. so the lava cause of death doesnt multiple mob drops it appears

**Comment by Nathat23** [comment]
Which version are you using? A similar bug was recently fixed.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: madmagic007 ***@***.***>
Sent: Tuesday, April 27, 2021 2:35:12 PM
To: Nathat23/StackMob-5 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Nathat23/StackMob-5] Drop counts are wrong when killed in lava (#213)


title, Stacked mobs dont drop the amount they should. example: 60 iron golems killed by lava only dropped 6 iron. when killed with a weapon by player they drop the correct amount.
Without this plugin they always drop the correct amount and the items dont drop in the lava. it could be that thius plugin causes them to drop in the lava?

**Comment by madmagic007** [comment]
updating to latest version fixed it, my bad
