### ISSUE TITLE
Stacked entities sent through portals are "corrupted".

### ISSUE THREAD

**Issue by Aurelien30000** [Nathat23/StackMob-5#215]
Hey,

I tried to figure out this issue for a few days, but it doesn't make sense.

**Explanations:**
An entity that travels through a portal is _desynchronized_, the entity stored in the stacked entity object isn't the right one (deduced from the fact its internal stack-size remains at 1 somehow).

I hope we'll be able to find out the cause and fix it! Please post any revelant comment you may have ;)

Thanks

**Comment by Nathat23** [comment]
If you spawn a normal entity and nametag it, once it goes through the portal it looses the nametag. Might be a spigot/paper bug?

**Comment by Nathat23** [comment]
> If you spawn a normal entity and nametag it, once it goes through the portal it looses the nametag. Might be a spigot/paper bug?

Doesn't occur on spigot. Seems to be a paper bug.

**Comment by Aurelien30000** [comment]
Oh, seriously, ty for testing, I'm gonna report this issue asap ;)

**Comment by Aurelien30000** [comment]
Sorry, wrong message, doesn't occur on paper (without stackmob) on my side.

**Comment by Nathat23** [comment]
Maybe it's something to do with the paper specific events?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Aurelien30000** [comment]
Certainly, it seems that events are called in a disorganized way, even not called or called several times 😅

**Comment by Nathat23** [comment]
Yeah so this doesn't occur at all on spigot, but it only occurs on paper while using stackmob.

**Comment by Aurelien30000** [comment]
Fixed in more recent versions.
