### ISSUE TITLE
/sm <arg> Commands doesnt work

### ISSUE THREAD

**Issue by pthoelken** [Nathat23/StackMob-5#218]
/sm update
/sm about 

... etc. doesnt work: 

![image](https://user-images.githubusercontent.com/12643853/120782031-e4ecfe80-c529-11eb-8633-0dc6dd94d116.png)

![image](https://user-images.githubusercontent.com/12643853/120782118-fa622880-c529-11eb-92b8-ba14af289408.png)

**Comment by Nathat23** [comment]
Try using /stackmob instead of /sm?

**Comment by pthoelken** [comment]
This works, yes. It's just a hint for the developer cauz the list of commands is maybe wrong?
