### ISSUE TITLE
Zombies stacking with baby zombies.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#22]
Version 5.0.2
Build 4: https://ci.ecocitycraft.com/job/StackMob-5/changes
Config: https://pastebin.com/beFhpY8G

Zombies are stacking with baby zombies.
Anyway to split them off. It's quite annoying when it comes to grinders.
Original report: https://ecocitycraft.com/forum/threads/zombie-stacking-various-forms-stacking-together.193961/

**Comment by Nathat23** [comment]
This has been fixed in the above commit.

**Comment by andrewkm** [comment]
Confirmed Fixed.
