### ISSUE TITLE
New health value is too high!

### ISSUE THREAD

**Issue by XC012** [Nathat23/StackMob-5#221]
>.... [16:04:40 WARN]: [StackMob] New health value is too high! Please report and include the message below.
>.... [16:04:40 INFO]: [StackMob] false,12.0,20.0,12.0,1.0
>.... [16:04:40 INFO]: [StackMob] 12.0,20.0,12.0

It says "Please report and include the message below." so yea

It spams a lot and its different sometimes:
>.... [16:05:44 WARN]: [StackMob] New health value is too high! Please report and include the message below.
>.... [16:05:44 INFO]: [StackMob] false,12.0,20.0,12.0,6.794719696044922
>.... [16:05:44 INFO]: [StackMob] 12.0,20.0,12.0
>.... [16:05:44 WARN]: [StackMob] New health value is too high! Please report and include the message below.
>.... [16:05:44 INFO]: [StackMob] false,12.0,20.0,12.0,6.794719696044922
>.... [16:05:44 INFO]: [StackMob] 12.0,20.0,12.0
>.... [16:05:46 WARN]: [StackMob] New health value is too high! Please report and include the message below.
>.... [16:05:46 INFO]: [StackMob] false,12.0,20.0,1

**Comment by Nathat23** [comment]
Are you using 5.5.6?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: XC0 ***@***.***>
Sent: Thursday, June 10, 2021 3:05:46 PM
To: Nathat23/StackMob-5 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Nathat23/StackMob-5] New health value is too high! (#221)


.... [16:04:40 WARN]: [StackMob] New health value is too high! Please report and include the message below.
.... [16:04:40 INFO]: [StackMob] false,12.0,20.0,12.0,1.0
.... [16:04:40 INFO]: [StackMob] 12.0,20.0,12.0

It says "Please report and include the message below." so yea

**Comment by XC012** [comment]
im using 5.5.5
