### ISSUE TITLE
1.17 - SPIGOT INCOMPATIBILITY

### ISSUE THREAD

**Issue by Aurelien30000** [Nathat23/StackMob-5#223]
Currently , Stackmob is not compatible at all with Minecraft 1.17 _(both Spigot and ~~Paper~~)_, due to huge/breaking changes about entity management.
We are waiting for fixes or other solutions.

Thanks for your understanding ;)

Spigot related issue: https://hub.spigotmc.org/jira/browse/SPIGOT-6547 **A temporary fix has been deployed to Stackmob.**
~~Paper related issue: https://github.com/PaperMC/Paper/issues/5871~~ **Issue fixed in a recent commit! Experimental build 3 doesn't include it, be aware.**

**Comment by Nathat23** [comment]
If the spigot events still work, then we could:
- Add chunks to hashset on chunk load
- Have task that checks the hashset for any chunks.
- Check the hashset if the chunks have any entities in them. Load those entities and remove chunk from hashset.

**Comment by Aurelien30000** [comment]
Right, however, entities seems loaded _little by little_, only checking once may cause skipping entities. This will need some tests later.
Performance impact would be also quite heavy.

**Comment by Aurelien30000** [comment]
Paper compatibility will be fixed in next experimental build, you can also build it locally, pulling latest changes.

**Comment by Aurelien30000** [comment]
Apparently Spigot finally fixed issue getting chunk entities by force loading them _(https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/ed7bba95fc031ca8b89d353426990b4bf7f9372f)_, your workaround may be removed.
