### ISSUE TITLE
Bug with picking up Axolotl

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-5#227]
When you try to take an axolotl out of its stack using a water bucket, instead of it taking one out of the stack it takes them all and renames the bucket to the name of the stack, e.g. 10 x Axolotl.

Paper 1.17.1 157
SM 5.6.2

**Comment by Nathat23** [comment]
Fixed in above commit, you can use builds from https://ci.codemc.io/job/Nathat23/job/StackMob-5/ for fix.

**Comment by LogGits** [comment]
You are an absolute legend. I'll test it out tonight ❤️
