### ISSUE TITLE
wait-to-stack breaks stacking.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#23]
Version 5.0.2
Build 5: https://ci.ecocitycraft.com/job/StackMob-5/changes
Current Config: https://pastebin.com/Sk9LTwpj

Use this setup:
https://i.imgur.com/6GFdfna.png
Zombies only ever go up to 3, remaining spawned do not stack.

HOWEVER, changing the config to this:
```
wait-to-stack:
  enabled: false
```

Basically disabling wait-to-stack, fixes the issue and they continue stacking.

**Comment by Nathat23** [comment]
Fixed in above commit.

**Comment by andrewkm** [comment]
This has not been fixed.
Please re-open @Nathat23 

The behaviour continues to be extremely weird.

- As soon as there are 3 in a stack, the remaining act very random.
- The most I've seen is a stacked 3 plus 3 singles.
- Afterwards they start disappearing, sometimes, one makes a 4 stack, and the rest continue to disappear.
- Sometimes one makes a 2 stack and instantly disappears, while the main stack continues to remain at 4.

Make yourself the following setup:
https://i.imgur.com/NJF8RIj.png

Right spawner: pig
Left spawner: zombie

And observe with following setup:

Build 10: https://ci.ecocitycraft.com/job/StackMob-5/changes
Current Config: https://pastebin.com/Sk9LTwpj
