### ISSUE TITLE
[1.18.1] Named Villagers loose name tag after turning into ZombieVillager 

### ISSUE THREAD

**Issue by nurdism** [Nathat23/StackMob-5#242]
Giving a villager a name tag and transforming them  into a Zombie Villager, they should keep the name, but this plugin is removing the name from the Zombie Villager.

**Comment by Nathat23** [comment]
are the villagers stacked?

**Comment by nurdism** [comment]
no they are not

**Comment by Nathat23** [comment]
From my testing unstacked villagers don't loose their name when converted to zombie villager.

Are you using default config?

**Comment by nurdism** [comment]
I've attached a [video](https://user-images.githubusercontent.com/420102/146822895-92e86df4-8bb7-4319-92f1-724352b7729e.mp4) of the issue. 

[config.yml](https://pastebin.com/mGJ4J0Z2)
Using: paper 1.18.1 83
And Version is StackMob 5.7.3

List of other plugins:
ProtocolLib
Vault 1.7.3
PlaceholderAPI 2.11.0
LuckPerms 5.3.86

**Comment by Nathat23** [comment]
Fixed in above commit, you can test with the builds at https://ci.codemc.io/job/Nathat23/job/StackMob-5/
