### ISSUE TITLE
[Suggestion] Use different way to change Mob Names

### ISSUE THREAD

**Issue by Chris6ix** [Nathat23/StackMob-5#247]
Hey, I just tried your plugin as I would like to use it on my server, but I have a big issue with it...it actually renames entities instead of just showing a different name...

The problem is that (as it told me already in console) it renames entities, and such will display when one of its entities dies in the console if `log-named-entity-deaths` is `true`...

The thing is that I want to keep that setting on, but also not have the console spam, so I wanted to ask you if you could change how the entities name works, to something like ["HoloMobHealth"](https://www.spigotmc.org/resources/holomobhealth-display-mob-health-damage-indicator-client-side-javascript-formatting.75975/) does?

This plugin also changes the name of mobs (Adds a health number to them) but without renaming the entity because it's "only Client Side" as the dev says. (I don't actually understand how he did that, but the plugin is open source, so you could check it out and try to implement something similar in StackMob)
This is A LOT better than actually renaming the entity, as it has the same effect but does not conflict with Named Entity Death messages and will let the server just normally despawn the entities (because they are not actually named) and such will not have the server filled with hundreds of named entities, which is not really a good thing to do...

Please tell me what you think of this, as I would really like to use your plugin, but the current way it handles entity names is just really not good and not ok for my server.

Kind regards,
Chris6ix :)

**Comment by Chris6ix** [comment]
bump.

**Comment by PhoenixCodingStuff** [comment]
Yup I would love to have this feature!

**Comment by Nathat23** [comment]
I am working on this for 5.8, see #253

**Comment by Nathat23** [comment]
@Chris6ix 
![2022-07-08_22 00 03](https://user-images.githubusercontent.com/10910702/178069844-e202a704-b314-4d40-9b07-610a23d52fb2.png)
