### ISSUE TITLE
bee does not work in blacklist.

### ISSUE THREAD

**Issue by mrcoffee1026** [Nathat23/StackMob-5#25]
This has no effect on bees:
```
# Types of entity which should not stack
types-blacklist: [villager,bee]

```
They still stack.  We don't want bees stacking since there's nothing to cause them to be more productive in stacks... it just reduces the population so that with my limit of 25 per stack... we'd need 75 bees to accomplish the exact same thing 3 bees would accomplish without stacking.  Since stacking them cannot be disabled, it's basically nerfing all bee populations on the server to no benefit.  If some other mechanics were also at work here like... what happens when stacked chickens lay eggs (like filling the hive faster, leaving the hive faster, etc)... then it wouldn't be so bad that stacking of bees can't be disabled.  But in this form it's just really irritating.

v5.0.2

**Comment by Nathat23** [comment]
You have to put the entity types in all caps.

**Comment by andrewkm** [comment]
Can confirm that entity types in all CAPS works correctly.
@mrcoffee1026 please see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html for valid entity names.

**Comment by mrcoffee1026** [comment]
ok thanks for that.
