### ISSUE TITLE
Allow stacked villagers to always drop items. - Not Building

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#250]
Latest change: https://github.com/Nathat23/StackMob-5/commit/25b3070a967f6dc520e0bccbeba3af259186cf9d
Isn't building.

`[ERROR] /var/lib/jenkins/workspace/StackMob-5/src/main/java/uk/antiperson/stackmob/listeners/DropListener.java:[26,31] incomparable types: org.bukkit.entity.Entity and org.bukkit.entity.EntityType`

**Comment by Nathat23** [comment]
Fixed
