### ISSUE TITLE
Spawner mob stack only

### ISSUE THREAD

**Issue by DarKuJolf** [Nathat23/StackMob-5#251]
Hello, I really enjoy the plugin but I would like to see added if possible a option that only mobs that spawn from spawners get stacked. Because I'm having a huge incompatibility with other plugins.

**Comment by Nathat23** [comment]
add SPAWNER to reasons-blacklist and enable reasons-blacklist-invert

**Comment by DarKuJolf** [comment]
Thanks for the very fast response @Nathat23.
