### ISSUE TITLE
exception while executing task 6443166

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#256]
Paper 1.19 Build 79
StackMob Latest (Built upon https://github.com/Nathat23/StackMob-5/commit/709f11339c9ad0d9f44f7cc0a247c5446ece98e8)

https://pastebin.com/raw/TXzwy6bb

**Comment by Nathat23** [comment]
Can you test the fix

**Comment by andrewkm** [comment]
Thank you for the fix, I wish I could test it but I genuinely don't know how to reproduce, just something we were getting in console.

I will monitor however and report back if it continues to occur once updated to the latest build. :)

**Comment by andrewkm** [comment]
We are still getting this.
https://pastebin.com/raw/xn2Dhbyh

Paper 1.19.1 Build 86
StackMob Latest (Built upon https://github.com/Nathat23/StackMob-5/commit/f810c7e3fb390ecf2cb7a8dbe637b3706f221a35)

**Comment by Nathat23** [comment]
has the above commit had any effect?

**Comment by andrewkm** [comment]
Will monitor and let you know. :)

**Comment by andrewkm** [comment]
It's actually spamming quite hard and much more now.
https://pastebin.com/raw/40CSWBNF

**Comment by Nathat23** [comment]
> It's actually spamming quite hard and much more now on every mob spawn. https://pastebin.com/raw/40CSWBNF @Nathat23
> 
> Stacking is also now completely broken.

it's unrelated to your original issue, but i've just fixed it in eb25ddb5ed75a7163005465a1c28be040eddf24c

**Comment by andrewkm** [comment]
Thanks, can confirm that's fixed.
Will continue to monitor original.

**Comment by andrewkm** [comment]
@Nathat23 I have not seen the error reported in this issue for the past 2 weeks a single time, so perhaps it's safe to say that is fixed. The only StackMob exception I see in the past two weeks is:

https://pastebin.com/raw/1fYcNhtv

Would you like this posted as a new issue?

**Comment by Nathat23** [comment]
> @Nathat23 I have not seen the error reported in this issue for the past 2 weeks a single time, so perhaps it's safe to say that is fixed. The only StackMob exception I see in the past two weeks is:
> 
> https://pastebin.com/raw/1fYcNhtv
> 
> Would you like this posted as a new issue?

Yeah make a new issue.

Closing.
