### ISSUE TITLE
Request: Add tamed/wild trait for Allay stacking.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#257]
Request: Add tamed/wild trait for Allay stacking.
Please also differentiate between "who" tamed the Allay if possible.

Also, general improvements around Allays would be really welcome.

**Currently**:
Multiple Tamed Allay tamed by different users will stack together, all but 1 item being held is lost.
The Allay's will be able to be killed by all players except 1 in the stack.

If Bob tames 3 Allay and Joe tames 3 Allay and John tames 3 Allay and they stack to 9, 2/3 of the users will be able to kill the stack, who these users are depends on who's allay is on the the "top" of the stack. If one of Bob's Allays is on the top of the stack he will not be able to damage the Allay stack.

Allay multi-stack takes on taming allegiance of one of the Allay, so all 9 become a stack of Allay tamed by Bob for example.

**Comment by Nathat23** [comment]
There isn't any allay API in bukkit so I can't do anything atm although I will see if I can get something PR'd

**Comment by andrewkm** [comment]
Thanks! :)

**Comment by andrewkm** [comment]
Fixed. :)
