### ISSUE TITLE
Task #60 for StackMob v5.8.1 generated an exception

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#259]
Paper 1.19 Build 79
StackMob Built upon https://github.com/Nathat23/StackMob-5/commit/709f11339c9ad0d9f44f7cc0a247c5446ece98e8

https://pastebin.com/raw/1fYcNhtv
(Just making a new issue as requested here: https://github.com/Nathat23/StackMob-5/issues/256) - Sorry I haven't been able to get around to it, been very busy lately.

**Comment by Nathat23** [comment]
Yeah I did fix this in c074e730cb2ef3539b11a3389fc73bc09f9eaee7 . Thanks anyway.

**Comment by andrewkm** [comment]
Ah alright, thank you! :)
