### ISSUE TITLE
Name tags piling up on forcestack.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#263]
Paper 1.19.2 Build 142
StackMob-5 built upon: https://github.com/Nathat23/StackMob-5/commit/e5b74af5308928a8135ff1d97d4dc6bf1d236b66 (latest)
Config: https://gist.githubusercontent.com/andrewkm/59cee1e0993e3b17001e8e886b317aa5/raw/d18275385fcb8961bad832b8ee785ba8300fffdd/gistfile1.txt

No idea how to explain, so again I'll just send a video lol:
https://youtu.be/KzolgUTozcQ

PS: I may be totally off here, and am simply misunderstanding the nametag-mode: JOIN config option.
Perhaps when it says "added" to the remaining entity, is exactly what it's doing above? If so, close and ignore.

**Comment by Nathat23** [comment]
Yes that is the intended functionality. The name tags from each entity are joined together.

**Comment by andrewkm** [comment]
Ah alright, thanks. :)
