### ISSUE TITLE
SilkSpawners spawners not working near stacked mobs.

### ISSUE THREAD

**Issue by cynikhavoc** [Nathat23/StackMob-5#267]
I have a sheep spawner using SilkSpawners plugin, and if there is stacked sheep near the spawner the spawner will not continue to spawn mobs.
Happens with cows aswell, but it does NOT happen with my creeper mob grinder that uses water to push them away from the spawners.

mcmmo: 2.1.218-snapshot
spigot: 3553-spigot-14a2382-ef09464 MC1.19
API version 1.19-RO.1-SNAPSHOT
SM version 5.8.4

**Comment by Nathat23** [comment]
this silkspawners? https://www.spigotmc.org/resources/silkspawners-versions-1-8-8-1-19-3.60063/
