### ISSUE TITLE
API Question

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-5#27]
So a plugin that i use, utilised stackmob's api and now returns:
```
[CoreArena] Plugin CoreArena v2.5.1 has failed to register events for class org.mineacademy.corearena.short. .a because uk/antiperson/stackmob/api/events/EntityStackEvent does not exist.
```
Is it possible if you could reintroduce the `uk/antiperson/stackmob/api/events/EntityStackEvent` file. Loving the plugin, keep up the great work!

**Comment by Nathat23** [comment]
Closing as this was added a while back.
