### ISSUE TITLE
Server hanging and kicking all players for about a minute.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#278]
We are getting random server hanging about twice a day due to StackMob recently.
The console shows as follows: https://pastebin.com/raw/xDh8wj7i

Paper 1.20.1 Build 193
ProtocolLib latest build compiled against: https://github.com/dmulloy2/ProtocolLib/commit/f0401acd2f498a0d41de2362abddb8427e2e3525
Stackmob latest build compiled against: https://github.com/Nathat23/StackMob-5/commit/4a82813e68f528ebe89452227085beaa69a0ee76
StackMob config: https://pastebin.com/NVs5ytkW

This all started happening after using a build with the following four changes:
**(This could however be completely unrelated...)**
https://i.imgur.com/25INavg.png

Here is a spark report from one of our servers during this issue:
https://spark.lucko.me/8jDhGk1pPg

Any help would be highly appreciated @Nathat23 .
Perhaps it's something with the latest Folia change? (Although we are not using Folia.)
https://i.imgur.com/jHPVFm6.png

Or perhaps something to do with the armor stands feature of Stackmobs?

**Comment by Nathat23** [comment]
The reason the folia code is running is because paper added folia's api.

I've removed folia stuff for now and moved it to a different branch.

**Comment by andrewkm** [comment]
Thanks, this has fixed the issues for us! :)
No more lag <3
