### ISSUE TITLE
Not working with 1.20.2

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#279]
When mobs stack in 1.20.2 - it crashes all players.

Paper 1.20.2 Build 217
StackMob compiled against latest commit: https://github.com/Nathat23/StackMob-5/commit/15e54bfc3c64d8c9410b8efefd11dda74a5d4309

Console errors as soon as stacking fires: https://pastebin.com/raw/sEKV3V9R
Player kick message: https://i.imgur.com/wDIclPF.png

@Nathat23 anything we can do about this on our end?

**Comment by Nathat23** [comment]
Are you using the 1.20.2 version of protocollib?

**Comment by Nathat23** [comment]
ea5b417  Should be fixed.

**Comment by andrewkm** [comment]
Of course, compiled against https://github.com/dmulloy2/ProtocolLib/commit/03d7be13d0f5409be9c77c0505a383636a0a1c32

**Comment by andrewkm** [comment]
> ea5b417  Should be fixed.

Will test shortly. :) that was quick! Just sat down for dinner haha.

**Comment by andrewkm** [comment]
Tested and confirmed fixed, appreciate the super fast response! <3
