### ISSUE TITLE
Bees still stacking regardless of Whitelist and Blacklist invert.

### ISSUE THREAD

**Issue by MrRayhonda** [Nathat23/StackMob-5#29]
Bees still stack even though i have it set for only Rabbit, cow, pig, chicken.

**To Reproduce**
make a white list and inverted blacklist for only farm animals. Spawn the amount of bees needed to stack. wait the time. Boom they stacked.

**Expected behavior**
bees aren't stacking.

**Screenshots/Videos**
https://ibb.co/WsCjTvL

**Bukkit/Spigot AND StackMob version:**
1.15.1 SM 5.0.2

**Additional context**
sorry to be back with an issue -.-

**Comment by Nathat23** [comment]
Is this still an issue? I saw your post on spigot for another plugin so...

**Comment by MrRayhonda** [comment]
yuup, that was from before you replied with my last issue. I was desperately looking for a replacement or solution bc so many ppl on the servers have massive mob farms so I needed a stack mob type plugin. And honestly the other one i found was a lot more basic and unfinished than I initially thought -.-. But yes this is still an issue and I have no idea why.

**Comment by andrewkm** [comment]
Please post your exact version (download link?)
As well paste your exact config so you can be properly assisted.

**Comment by MrRayhonda** [comment]
Bukkit/Spigot AND StackMob version:
1.15.1 SM 5.0.2

Config: https://pastebin.com/1VBag4LP

**Comment by Nathat23** [comment]
Works as intended for me. Are you fully restarting the server after making these changes?

**Comment by MrRayhonda** [comment]
I must be some kind of stupid xD I seriously thought i restarted the server when updating it but it seems that no, bees are not stacking! :D sorry about that. Thanks so much! I feel dumb as heck but i'm really happy it's no longer happening
