### ISSUE TITLE
Is this okay to use?

### ISSUE THREAD

**Issue by Callahhh** [Nathat23/StackMob-5#3]
I know it's still in development, but is it alright to use on a 1.15 paper server at the moment?

**Comment by Nathat23** [comment]
Should be - the core functionality is implemented. The only things needed until release will be cosmetic features (like translations and the stacking tool.) 

Features may be liable to change however between commits.

**Comment by Callahhh** [comment]
Not sure what I'm doing wrong, mvn clean install gives me this: https://imgur.com/a/q2ABGSr but none of them load/work when putting them on a server?

**Comment by Nathat23** [comment]
are you getting any errors?

**Comment by Callahhh** [comment]
nope

**Comment by Nathat23** [comment]
can you pastebin the entire output when you run maven?

**Comment by Callahhh** [comment]
andddd never mind, it works. I was in the wrong server folder lol. Sorry!

**Comment by adroslice** [comment]
When will this versions official release be? I just got done configuring the 4.0.2 version when I read a whole bunch of bad things regarding performance. Will this work for versions before 1.15? I'm using Paper 1.13.2.

**Comment by Nathat23** [comment]
> When will this versions official release be? I just got done configuring the 4.0.2 version when I read a whole bunch of bad things regarding performance. Will this work for versions before 1.15? I'm using Paper 1.13.2.

This will for 1.15 only.
