### ISSUE TITLE
WAY to many slimes

### ISSUE THREAD

**Issue by CaszGamerMD** [Nathat23/StackMob-5#31]
Slime multiplier is off, slimes still multiply on death.

big issue is stacked large slime, dies -kills one of stack- still multiplies med slime count, then med slime die and produce same effect, if they stack which they do.

https://youtu.be/Vaa34X_Wvlo
freshly uploading video if problem

config:
[config.txt](https://github.com/Nathat23/StackMob-5/files/4085170/config.txt)

causing big lag

**Comment by LogGits** [comment]
Woah that looks crazy!

**Comment by Nathat23** [comment]
If this is a big issue, for now you can disable 'slime-split' in the 'events' section for now to prevent this.

**Comment by CaszGamerMD** [comment]
I have

**Comment by CaszGamerMD** [comment]
Issue persists

**Comment by andrewkm** [comment]
Slimes in general are garbage on 1.14.4+
@CaszGamerMD highly recommend just disabling slime spawning on your server.
We had the exact same problem with and without stackmob, with and without slime-split enabled/disabled.

**Comment by Aurelien30000** [comment]
I think this functionnality should be removed or we should force a fixed amount to spawn and a fixed amount to die.

**Comment by Nathat23** [comment]
The issue here is that stackmob multiplies the slimes as if every entity in the stack dies, regardless the actual amount that died.
