### ISSUE TITLE
Eggs not corresponding to the chickens in stack

### ISSUE THREAD

**Issue by MrRayhonda** [Nathat23/StackMob-5#33]
**Describe the bug**
after more testing I have witnessed a stack of 88 chickens lay an egg. it took quite a while but I know that chickens can lay 1 egg between every 5-10 mins. This doesn't seem to multiply by the amount of chickens in a stack like it did in older version of Stackmob. A lot of people are complaining their chicken farms don't work because of the plugin yadda yadda. So yeah, 1 stack of 88 chickens or more lays only 1 egg every 5-10 mins instead of 88 randomly between those times. Any way to fix that?

**To Reproduce**
Stack a bunch of chickens and wait.

**Expected behavior**
chickens lay a proper amount of eggs relative to the amount of chickens in the stack.

**Screenshots/Videos**
just a single egg here. everything else can be ignored since it's from other stuff. behind the chest is a chicken stack of 88 on top of a hopper.
https://i.ibb.co/n85wB9C/2020-01-21-15-56-23.png

**Bukkit/Spigot AND StackMob version:**
1.15.2 SM: 5.0.2

**Additional context**
sorry to have so many bugs n bothering u. Ppl love this plugin on the server and so do i but they want pretty particular functionality etc. >.<

**Comment by Nathat23** [comment]
Fixed in above commit.

**Comment by MrRayhonda** [comment]
will an updated jar be posted to spigot or do i need to add the code somewhere? ^^ Thanks for the fix! Keep up the great work!

**Comment by Nathat23** [comment]
You can download a development build from https://ci.ecocitycraft.com/job/StackMob-5/

**Comment by MrRayhonda** [comment]
added and reloaded the server ^^ so no new config n stuff it seems which is awesome. I'll keep you posted :D

**Comment by MrRayhonda** [comment]
it woooooorks!
