### ISSUE TITLE
Stacking mobs that already exist.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#38]
So I have quite a bit of an issue and am unsure as to how I should go about getting around it.

I have a world with a very large amount of mobs, that are all name tagged in several places. I’d like to enable stacking in this world (we had the world blacklisted for years) however when I do so (and indeed I did restart, not just /sm reload)... only newly spawned mobs (we do not blacklist any stack reasons) stack.

So say I have a sheep pen with 10 old name tagged sheep prior to removing the world from the blacklist, only newly spawned sheep in that pen will stack. The old ones never do. There is basically a stack of 30+ in the middle of 10 individual sheep, and regardless of what I do I cannot get those ten to stack.

I have also verified that newly spawned mobs even if name tagged do get stacked, it’s the ones prior to removing the blacklist that don’t.

Now of course I realize you cannot be scanning the entire world for mobs as that would kill performance.

Anyways, I need some sort of solution please.

Perhaps there is an option or command I’m not aware of? And if not, can we get some sort of, /sm forcestack command.

This command would go through all loaded chunks and stack all mobs, I would then run this command on an interval of one hour obviously understanding it would cause lag while it’s executing.

As well can you add an option somehow to take old mobs into consideration.

I actually really hope this is nothing more than a bug, but if not please find us a solution <3.

PS: A forcestack command would be extremely useful, yes it would be laggy but it would be the server owners responsibility to understand that. Please consider, this would literally save my old world.

**Comment by andrewkm** [comment]
@Nathat23 will you be merging 5.1 into master?
Curious as I've done tons of testing and it works quite well, and I'd like to use some of the new changes you're adding such as: https://github.com/Nathat23/StackMob-5/pull/37

**Comment by andrewkm** [comment]
Tested this in depth on @Aurelien30000 's branch, works great :)

**Comment by Nathat23** [comment]
PR was merged into master so this can be closed.
