### ISSUE TITLE
Named entity stacking config.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#41]
This PR introduces not stacking renamed entities:
https://github.com/Nathat23/StackMob-5/commit/a5c740ee61d0c45f1e4c91f49907f9786519f6a6

This absolutely needs a config as some of us specifically rely on stacking renamed (nametags) entities.
@Aurelien30000

**Comment by Aurelien30000** [comment]
My Pr only disabled stacking for renamed entities by nametags indeed, I can anyway implement what you expect but I think it’s strange 🤔

**Comment by andrewkm** [comment]
What’s strange to one server is required on another. Not all servers operate the same, forcing something to act completely different without configuration is not right.

**Comment by Aurelien30000** [comment]
I'll make it configurable this week-end, and sorry, it just made sense in my mind...

**Comment by Aurelien30000** [comment]
Done ! But I didn't have time to try it, sorry, so please test it and confirm if the option works correctly :) Thanks !

[StackMob-5.0.2.zip](https://github.com/Nathat23/StackMob-5/files/4172289/StackMob-5.0.2.zip)

**Comment by andrewkm** [comment]
I will need to wait until it’s pulled so I can compile it :).

Thanks!

**Comment by Aurelien30000** [comment]
Don't need to wait, you can just download the file I joined in my last message ^^
Or compile from my fork !

**Comment by andrewkm** [comment]
@Aurelien30000 this is fixed on your branch :)

**Comment by Nathat23** [comment]
Closing as this was fixed in the merged PR.
