### ISSUE TITLE
Villagers stacking removes trades

### ISSUE THREAD

**Issue by kyle1elyk** [Nathat23/StackMob-5#43]
With the default configuration, when players have a village with enough Villagers of the same profession to stack they do without preserving the trades. Also, this messes with the ecosystem where say there are 5 farmers which supply food to the rest, after the stack there is only a single farmer.
Suggestion would be to have villagers default to being blacklisted in the config.

**Comment by Aurelien30000** [comment]
You should create a Pull Request, I can include in mine if you don't know how to do :)

**Comment by Nathat23** [comment]
Closed as the corresponding pull request has been merged.
