### ISSUE TITLE
sm forcestack isn't stacking old unnamed mobs.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#44]
5.1 branch:
/sm forcestack is only stacking old named mobs.
It is not stacking old unnamed mobs. (as in those in a world where stacking was previously disabled.)

**Comment by Aurelien30000** [comment]
Indeed, if we force entities to stack, should be unstacked entities, and we should ignore them if they are already stacked :thinking: 
https://github.com/Nathat23/StackMob-5/commit/07fb3ea11dd28b89a28f1f9d680739b8280b9562#diff-0bab8348379725d714038f04b8a1bd86R26

**Comment by andrewkm** [comment]
@Aurelien30000 if you’re able to throw something together for this would be amazing.

We basically need ALL entities, regardless of stacked, not stacked, name tagged, not name tagged, to stack when issuing the all mighty force stack :).

PS: The command doesn’t shoot a confirmation message as well. Would be nice to throw one in.

**Comment by Aurelien30000** [comment]
> @ Aurelien30000 si vous êtes capable de jeter quelque chose ensemble, ce serait incroyable.
> 
> Nous avons essentiellement besoin de TOUTES les entités, qu'elles soient empilées, non empilées, étiquetées par un nom, pas étiquetées par un nom, pour être empilées lors de l'émission de la puissante pile de force :).
> 
> PS: La commande ne tire pas non plus un message de confirmation. Ce serait bien d'en jeter un.

I will try when I'll get home this evening or this week-end ! :)

**Comment by andrewkm** [comment]
Also with what you said about ignoring if already stacked, no those shouldn’t be ignored, as name tagged mobs are considered as stacked, since stacking goes off the tag. @Aurelien30000

**Comment by andrewkm** [comment]
Here's a video showing the issue.
https://www.youtube.com/watch?v=zB3NAj37p-E&feature=youtu.be

**Comment by Aurelien30000** [comment]
> Here's a video showing the issue.
> https://www.youtube.com/watch?v=zB3NAj37p-E&feature=youtu.be

After running /sm forcestack, do the entities have the NBTtag of the stack in their data ? (You can see that with /data)

**Comment by andrewkm** [comment]
@Aurelien30000 of you can merge 5.1 into your branch... I’ll set up a Jenkins for us and then can help you test everything, will be much easier :). Main dev seems to be afk lately.

**Comment by andrewkm** [comment]
@Aurelien30000 got you setup here.
Once you merge 5.1 - we can mess with the changes.
It polls your repo every 5 minutes so should be pretty quick :)

**Comment by Aurelien30000** [comment]
Hum, after testing (https://youtu.be/nt1ZsBYb5Ug), I think something is overriding stack system, or maybe just your configuration forbid that ?

**Comment by andrewkm** [comment]
Please post the config you’re testing with.

**Comment by Aurelien30000** [comment]
Here is -> [config.zip](https://github.com/Nathat23/StackMob-5/files/4203655/config.zip)

**Comment by andrewkm** [comment]
I've found the issue with **/sm forcestack**
The problem is if you use:
```
stack:
  threshold:
    enabled: false
```
then this breaks /sm forcestack.
In face threshold at false has always caused issues with stackmob.

Setting it to true fixes /sm forcestack.
Definitely a bug, but I can live with it. I'll just keep it at true.

Try it with your config, set your threshold to false, and /sm forcestack will not force the stacking of old mobs. @Aurelien30000

**Comment by Aurelien30000** [comment]
> I've found the issue with **/sm forcestack**
> The problem is if you use:
> 
> ```
> stack:
>   threshold:
>     enabled: false
> ```
> 
> then this breaks /sm forcestack.
> In face threshold at false has always caused issues with stackmob.
> 
> Setting it to true fixes /sm forcestack.
> Definitely a bug, but I can live with it. I'll just keep it at true.
> 
> Try it with your config, set your threshold to false, and /sm forcestack will not force the stacking of old mobs. @Aurelien30000

Maybe this line @andrewkm https://github.com/Nathat23/StackMob-5/issues/44#issuecomment-586579335 I will try to fix it, I'll let you know an commit to enable you to test :) Thanks !

**Comment by andrewkm** [comment]
@Nathat23 was this fixed?
