### ISSUE TITLE
sm forcestack removing nametag son singular mobs.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#45]
1. Spawn one mob.
2. Ensure no mobs are around.
3. Name the mob.
4. /sm forcestack
5. The named mob becomes unnamed.

Sm forcestack should not be removing name tags of singular mobs.
It's a new system so will definitely take some time to sort out properly :)

@Aurelien30000 - Let's see if we can get this one too. :D

**Comment by Aurelien30000** [comment]
@andrewkm Singular mobs can be considered stacked, here is the importance of the option for stack data removing but we could add another condition to the command.

**Comment by andrewkm** [comment]
@Aurelien30000 ok :)

**Comment by Aurelien30000** [comment]
So do you need this option ? In the command syntax or in the config ? ^^

**Comment by andrewkm** [comment]
Would be nice to have it in the config :)
@aurelien30000

**Comment by Aurelien30000** [comment]
@Nathat23 I request your opinion about that :) Thanks !

**Comment by Nathat23** [comment]
Would it not be better apart of the command syntax, since it is a command? Like it should be a default behavior, but to also have an argument to override ignoring those mobs if needed.

**Comment by andrewkm** [comment]
Yes that would be better.

**Comment by andrewkm** [comment]
Any updates on this @Nathat23

**Comment by Nathat23** [comment]
@andrewkm Working on it. Btw your ci now requires authentication?

**Comment by andrewkm** [comment]
Oops, re-added the public stuff to no authentication. Was working on some security updates for Jenkins and got side tracked lol.
