### ISSUE TITLE
Nametag of dead entity

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-5#46]
Can the nametag from the dead entity be removed or hidden when it's spawned.
This becomes annoying to players:
https://gyazo.com/852b590b96930c53e29f1f796d378132

**Comment by Aurelien30000** [comment]
This is just visual, for the server the entity is already non existent, sorry, I don't think there is a way to fix that :/

**Comment by Nathat23** [comment]
It could be perhaps fixed by setting the display name to null when killed? I will have to test.

**Comment by Aurelien30000** [comment]
> It could be perhaps fixed by setting the display name to null when killed? I will have to test.

Indeed, but after testing, the entity is still affected by tag task and a nametag can sometimes "come back" ^^

**Comment by kyle1elyk** [comment]
Is the entity considered dead at that point? As in, could entity.isDead() be used to check in TagTask whether or not it should get a name? I was able to get the name to disappear by setting the custom name to an empty string on death, and the tag comes back but without a count.
![Screenshot (35)](https://user-images.githubusercontent.com/15645345/74940892-22268f00-53c0-11ea-8686-cb5114b2901a.png)

**Comment by Nathat23** [comment]
Closing since the pull request was merged.
