### ISSUE TITLE
Dupe? 

### ISSUE THREAD

**Issue by Callahhh** [Nathat23/StackMob-5#5]
> if you give a trident (including enchanted trident) to a stacked mob drowned, all of the stacked mobs will have a trident, meaning that when you kill them they will drop duplicates of the original trident.

I feel like there's a config setting, but nothing is popping out to me. Thoughts?

**Comment by Nathat23** [comment]
There isn't a config setting to do this. Entity hand item and armor drops shouldn't supposed to be duplicated, so I'm not sure why that's occurring. Can you provide your config file so I can attempt to replace?

**Comment by Callahhh** [comment]
https://pastebin.com/6chdfPte

**Comment by Nathat23** [comment]
Hmm I'm not sure why that would be happening then. Can you provide a video of this?

**Comment by andrewkm** [comment]
How exactly are you give a stacked mob of drowned a trident?
I am unable to reproduce this at all.
Stacked drowned / don't stack with trident equipped drowned.

Please provide more details for reproduction.

**Comment by Callahhh** [comment]
1. Have a drowned that has no items but can pick them up
2. Have him stack so that he is more than 1x
3. Drop him a trident, he picks it up
4. When killing the stack, every mob killed will have a chance to drop the held item
5. On killing the drowned, the item in hand transfers to the next mob, even when it is also dropped
6. You can prove this is the same item as if you drop a trident on the drowned in a stack and it is enchanted, the next trident the next drowned has is also enchanted.

Killing a 50x with an enchanted trident will drop the same trident every time but still give the trident to the next drowned in the stack

**Comment by andrewkm** [comment]
@Callahhh what StackMob command are you using to spawn a drowned that can pickup a trident.
I literally still cannot reproduce this.

**Comment by Callahhh** [comment]
Fixed in https://github.com/Nathat23/StackMob-5/commit/a5990309899899fb6bf4ee92a42ac4895bb6b000
