### ISSUE TITLE
FullSlice

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-5#51]
A FullSlice or something similar that allows you to unstack the whole entity e.g. spawn its amount of stack, would be nice to have. It's hard to work with mobs such as bees when trying to unstack.

**Comment by Aurelien30000** [comment]
Whould be great I think ^^

**Comment by Nathat23** [comment]
A year later but has been added in 9ce005eeb77a938e66cd8752f6e72c7489613e03
