### ISSUE TITLE
Scute count not being multiplied by stack count

### ISSUE THREAD

**Issue by mrcoffee1026** [Nathat23/StackMob-5#52]
Stack count has no effect on scute count on turtle maturation, one scute per stack is all that is possible.
v5.0.2

**Comment by Aurelien30000** [comment]
@mrcoffee1026 I fixed this issue, you can use my build currently waiting for a public release https://ci.ecocitycraft.com/job/StackMob-5.1-Aurelien30000/ :)

**Comment by mrcoffee1026** [comment]
sweet thank you for the link, hope your pr gets accepted, i'll use it till it either does or the op puts a similar patch in place.

**Comment by Nathat23** [comment]
Closing, since the PR was merged.
