### ISSUE TITLE
Throwing several errors

### ISSUE THREAD

**Issue by thecenters** [Nathat23/StackMob-5#54]
I'm getting an error related to mob health. Saying something along the lines of "Health must be between 0 and 20 but instead was 40.2342365232"

This is another error I'm getting after lowering the mob cap on the server.

21.02 12:39:19 [Server] WARN [StackMob] Task Nathat23/StackMob-3#103 for StackMob v5.0.2 generated an exception
21.02 12:39:19 [Server] INFO java.lang.IllegalArgumentException: Stack size cannot be more than the configured stack size!
21.02 12:39:19 [Server] INFO at uk.antiperson.stackmob.entity.StackEntity.setSize(StackEntity.java:35) ~[?:?]
21.02 12:39:19 [Server] INFO at uk.antiperson.stackmob.entity.StackEntity.setSize(StackEntity.java:23) ~[?:?]
21.02 12:39:19 [Server] INFO at uk.antiperson.stackmob.entity.StackEntity.merge(StackEntity.java:179) ~[?:?]
21.02 12:39:19 [Server] INFO at uk.antiperson.stackmob.tasks.MergeTask.run(MergeTask.java:49) ~[?:?]
21.02 12:39:19 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-66]
21.02 12:39:19 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-66]
21.02 12:39:19 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-66]
21.02 12:39:19 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:423) ~[patched_1.15.2.jar:git-Paper-66]
21.02 12:39:19 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-66]
21.02 12:39:19 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-66]

**Comment by Nathat23** [comment]
Fixed in above commit.
