### ISSUE TITLE
Stacked Mob "Targeting" Setting Ignored

### ISSUE THREAD

**Issue by JammMusic** [Nathat23/StackMob-5#55]
**Describe the bug**
Mob AI does not disable for stacked mobs, even when mob targeting is disabled.

**To Reproduce**
Allow hostile mobs to stack and they will attack you.

**Expected behavior**
Stacked mobs should have no AI if the targeting feature is disabled.

**Bukkit/Spigot AND StackMob version:**
Spigot 1.15.2
StackMob 5.0.2

**Comment by JammMusic** [comment]
Is this being looked into? It's a huge problem. If I'm the only one experiencing it then maybe there's something wrong with my config.

**Comment by Nathat23** [comment]
Can you provide your config?

**Comment by Aurelien30000** [comment]
Listener is not registered because of the config option `"disable-targeting.enabled"` but check is done on `"events.disable-targeting.enabled"` that doesn't exist, false is returned (default), listener isn't registered ^^
We should also check TargetReason to only players reason, as indicated in the config.

**Comment by Nathat23** [comment]
> Listener is not registered because of the config option `"disable-targeting.enabled"` but check is done on `"events.disable-targeting.enabled"` that doesn't exist, false is returned (default), listener isn't registered ^^
> We should also check TargetReason to only players reason, as indicated in the config.

nice spot, I will fix this.

**Comment by Nathat23** [comment]
@JammMusic You can test the fix by using the latest build from https://ci.ecocitycraft.com/job/StackMob-5/

**Comment by JammMusic** [comment]
Thank you so much.
