### ISSUE TITLE
Breeding experience

### ISSUE THREAD

**Issue by tblazek98** [Nathat23/StackMob-5#57]
**Describe the bug**
When you breed a mob such as cow, pig, chicken, etc. it splits correctly, but I am not getting the experience I normally would when I breed an animal.

**To Reproduce**
1. Give stacked chicken seeds
2. No experience given :(

**Expected behavior**
What I expect to happen is get the experience for how many animals I bred

**Bukkit/Spigot AND StackMob version:**
Spigot

**Comment by Nathat23** [comment]
Implemented in ddf3824e9838375c009d8dafda04506892fc4d4d
