### ISSUE TITLE
1.15

### ISSUE THREAD

**Issue by jere62smi** [Nathat23/StackMob-5#6]
Hello,

I would like to know if the plugin will be compatible with 1.15 because currently, the stack of mobs no longer work despite the fact that the plugin loads correctly. I managed to get this in my logs, I use the latest version of paper # 8 in 1.15.
https://pastebin.com/Ks9vWU8G

**Comment by jere62smi** [comment]
I do not use mysql storage with your plugin but I really cannot configure the new version. Here is what my file looked like with the old version, I can no longer stack only the mobs that I had predefined and the mobs kill themselves 2 by 2.
http://bin.mc-imperia.fr/bE8IGczMdU

**Comment by Nathat23** [comment]
Try this: https://pastebin.com/SaKGpLiv

**Comment by jere62smi** [comment]
Hi, your config works, thank you however, the old mobs are no longer stacked. What to do ? There is a way to keep the old mobs because I don't want to put this in place on my prod server if it doesn't work anymore.

**Comment by Nathat23** [comment]
If you run the command '/sm about' do you see 'StackMobBridge' mentioned anywhere?

**Comment by jere62smi** [comment]
Okay I succeeded suddenly, everything seems to work, on the other hand the option "display-name" with as argument "ALWAYS", "HOVER" and "NEARBY" do not seem to work correctly, in my case anyway, the arguments do not do not always seem to do what is asked, nothing very annoying after.
Thank you for you help ! :)

**Comment by jere62smi** [comment]
Since I removed StackMobBridge for the conversion of my old mobs, it no longer works, none of my new mobs manage to stack, yet I have set your configuration correctly.

**Comment by jere62smi** [comment]
I also take this opportunity to send you an error that I managed to produce.
http://bin.mc-imperia.fr/fwicJe18lx

**Comment by Nathat23** [comment]
> Since I removed StackMobBridge for the conversion of my old mobs, it no longer works, none of my new mobs manage to stack, yet I have set your configuration correctly.

Yes I just noticed this on my test server. I must of broke something.

**Comment by jere62smi** [comment]
Other error http://bin.mc-imperia.fr/o0yw1tgpx3

**Comment by jere62smi** [comment]
I tested the latest version by compiling it and I no longer have the errors that I reported previously, however and I do not know if you fixed it but in any case its does not work it is the fact that mobs get stacks since I put the conversion between 4.0 and 5.0 and I still left StackMobBridge

**Comment by Nathat23** [comment]
So do new entities not stack? Or is it just the old ones?

**Comment by jere62smi** [comment]
Only the new ones, for the old ones everything works.

**Comment by jere62smi** [comment]
So do you have a solution? However, I used your configuration file that you sent me above.

**Comment by Nathat23** [comment]
Could you specify what you are doing? It seems to work fine with the config above.

**Comment by jere62smi** [comment]
I am just trying to group together hens for example in format in pack of 5 hens in one but I may spawn hundreds and wait, they do not merge in pack of 5 as I specified in the configuration.

**Comment by Nathat23** [comment]
I will close this issue in lieu of #12 so we don't have duplicates.
