### ISSUE TITLE
Stacked Mob AI

### ISSUE THREAD

**Issue by JammMusic** [Nathat23/StackMob-5#62]
**Describe the bug**
Stacked mobs still have AI when set not to in the config.

**To Reproduce**
Disable stacked mob AI in config and go near a stacked hostile mob.

**Expected behavior**
Stacked hostile mobs should not attack players or have any AI.

**Bukkit/Spigot AND StackMob version:**
Spigot 1.15.2
StackMob 5.0.2

**Comment by Nathat23** [comment]
Duplicate of your previous issue? #55
