### ISSUE TITLE
Experience multiplier

### ISSUE THREAD

**Issue by Zachy24** [Nathat23/StackMob-5#66]
Hello. I'm trying to use the plugin so that when a stack of mobs dies (we have all set as the top priority), it drops the amount of exp respective to the stack size. I see there are multiplier-min and multiplier-max settings, however adjusting these does not seem to have any effect and killing the stack just gives one level worth of xp. I wish for it to just drop the equivalent exp of a `vanilla mob experience drop * stack size`. How is this achievable? Thanks!

**Comment by Nathat23** [comment]
This has been fixed, see #80
