### ISSUE TITLE
Installed it but not working

### ISSUE THREAD

**Issue by GNFxo** [Nathat23/StackMob-5#67]
Hey so when I do /plugins its green which should mean its working try stacking and nothing stacks?

**Comment by Nathat23** [comment]
Can you provide the full error?

**Comment by GNFxo** [comment]
I sent this pastebin https://pastebin.com/pvA034jm

**Comment by Aurelien30000** [comment]
StackMob 5 is onyl designed for 1.15 ^^

**Comment by GNFxo** [comment]
Have you got a version that'll work for 1.13.2 as i did install your version for it but that wouldn't work it would show up red as for the 1.15 would show green

**Comment by Aurelien30000** [comment]
Try v3 or v4 or Stackmob :)
