### ISSUE TITLE
Disastrous performance of DataContainer...

### ISSUE THREAD

**Issue by Aurelien30000** [Nathat23/StackMob-5#70]
![image](https://user-images.githubusercontent.com/43724816/78473078-098af200-773e-11ea-8a49-090748c50f45.png)

With lots of entity spawning, we can notice a big thread use by setting a value of a DataContainer :/

**Comment by Nathat23** [comment]
Well its the payoff for the convenience of the NBT API I guess.

**Comment by Aurelien30000** [comment]
Set it async is unsafe, I'll close this issue because it's almost useless, unless other people complain opf that in the future... Thanks !
