### ISSUE TITLE
Entity Tag NullPointerException

### ISSUE THREAD

**Issue by heyyitstim** [Nathat23/StackMob-5#72]
Stack Mob v5.0.2
https://ci.ecocitycraft.com/job/StackMob-5.1-Aurelien30000/

Blazes are spawning from a mob spawner. Error seems to show up as they spawn.
Some of them are stacking, others have the nametag "Blaze" in white text and are not stacking with the mobs next to them.

`06.04 18:24:37 [Server] Server thread/WARN [StackMob] Task #288 for StackMob v5.0.2 generated an exception
06.04 18:24:37 [Server] INFO java.lang.NullPointerException: null
06.04 18:24:37 [Server] INFO at uk.antiperson.stackmob.entity.Tag.update(Tag.java:31) ~[?:?]
06.04 18:24:37 [Server] INFO at uk.antiperson.stackmob.entity.StackEntity.setSize(StackEntity.java:41) ~[?:?]
06.04 18:24:37 [Server] INFO at uk.antiperson.stackmob.entity.StackEntity.setSize(StackEntity.java:23) ~[?:?]
06.04 18:24:37 [Server] INFO at uk.antiperson.stackmob.entity.StackEntity.incrementSize(StackEntity.java:84) ~[?:?]
06.04 18:24:37 [Server] INFO at uk.antiperson.stackmob.entity.StackEntity.merge(StackEntity.java:188) ~[?:?]
06.04 18:24:37 [Server] INFO at uk.antiperson.stackmob.tasks.MergeTask.run(MergeTask.java:49) ~[?:?]
06.04 18:24:37 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 18:24:37 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 18:24:37 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 18:24:37 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 18:24:37 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 18:24:37 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 18:24:37 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

**Comment by Nathat23** [comment]
Are you using the latest MythicMobs (4.9)?

**Comment by heyyitstim** [comment]
> Are you using the latest MythicMobs (4.9)?

Yes

**Comment by Nathat23** [comment]
I'm assuming that you have configured blazes to be overridden in the VanillaMobs.yml file?

**Comment by heyyitstim** [comment]
> I'm assuming that you have configured blazes to be overridden in the VanillaMobs.yml file?

Yeah, gave them more health and a stronger attack.
Is that what's causing the issue?

**Comment by Aurelien30000** [comment]
I don't think, these things don't impact the displayname, maybe...

**Comment by Nathat23** [comment]
> > I'm assuming that you have configured blazes to be overridden in the VanillaMobs.yml file?
> 
> Yeah, gave them more health and a stronger attack.
> Is that what's causing the issue?
Yes, should be fixable.
> I don't think, these things don't impact the displayname, maybe...
The issue here is that the blazes are MythicMobs. However there is no custom displayname so we get the NPE.

**Comment by Nathat23** [comment]
This has been fixed, you can use the latest build from https://ci.ecocitycraft.com/job/StackMob-5/ to resolve this issue.

**Comment by heyyitstim** [comment]
> This has been fixed, you can use the latest build from https://ci.ecocitycraft.com/job/StackMob-5/ to resolve this issue.

Thank you! Seems like it has been fixed. Though, not sure if you're aware, it looks like the error described [here](https://github.com/Nathat23/StackMob-5/issues/26) is still present with the latest build.

`07.04 18:39:38 [Server] Server thread/ERROR Could not pass event EntityDeathEvent to StackMob v5.1.0
07.04 18:39:38 [Server] INFO org.bukkit.event.EventException: null
07.04 18:39:38 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:721) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1328) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1277) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1124) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(SourceFile:69) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1085) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1545) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1879) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:68) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:13) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
07.04 18:39:38 [Server] INFO Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 20.0(31.0)
07.04 18:39:38 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:109) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
07.04 18:39:38 [Server] INFO at uk.antiperson.stackmob.entity.death.KillStepDamage.onSpawn(KillStepDamage.java:30) ~[?:?]
07.04 18:40:09 [Multicraft] Skipped 6 lines due to rate limit (30/s)`
