### ISSUE TITLE
[Bug] NO LAG FIX?

### ISSUE THREAD

**Issue by msmanui** [Nathat23/StackMob-5#75]
Hi. Lets supose instead of having 10 zombies spread in a chunk, i will have 10 zombies in 1...   (Plugun function)

But if those 10 zombies spawn naturally, why they wont spawn again? as now its only 1 zombie but for us says 10 because it a plugin feature... 

So its like an infinite process that never stop

**Comment by Nathat23** [comment]
This depends on your server configuration. With plugins such as FarmLimiter, you can limit the amount of the entities in an area. For example if you limit 20 entities to a chunk, with StackMob, you can fit many more entities (20 x max stack size) into the same area with little performance penalty.

**Comment by msmanui** [comment]
> This depends on your server configuration. With plugins such as FarmLimiter, you can limit the amount of the entities in an area. For example if you limit 20 entities to a chunk, with StackMob, you can fit many more entities (20 x max stack size) into the same area with little performance penalty.

But lets supose they spawn randomly 10 zombies? And they stack all in one... So my question is, minecraft spawns would detected still there is 10 zombies even they are stacked?

**Comment by Aurelien30000** [comment]
No, server detects only 1 zombie, but after all my time using this plugin and if you use a FarmLimiter and a min amount to stack entities, there isn't any visible impact (on my side) :)

**Comment by msmanui** [comment]
> No, server detects only 1 zombie, but after all my time using this plugin and if you use a FarmLimiter and a min amount to stack entities, there isn't any visible impact (on my side) :)

So can this plugin reduce lag as it's always spamming mobs constantly? Even they are stacked, they still gona be stacked.. Useless

**Comment by Aurelien30000** [comment]
> > No, server detects only 1 zombie, but after all my time using this plugin and if you use a FarmLimiter and a min amount to stack entities, there isn't any visible impact (on my side) :)
> 
> So can this plugin reduce lag as it's always spamming mobs constantly? Even they are stacked, they still gona be spawned others.. Useless

If you use it according to your needs (with a minimum) and with an adapted configuration, yes, this plugin helps to reduce lag on a server (absolutely sure with animals' farm), entities are less abundant ^^
