### ISSUE TITLE
Naturally Spawned Mobs Stacking

### ISSUE THREAD

**Issue by SmexyDuk** [Nathat23/StackMob-5#79]
Is there any way to make only-spawner mobs to stack? Every single mobs in the server stacks and it causes a huge lag. Its better if theres an option where only spawner mobs can stack. I hope to get help, thank you!

**Comment by Nathat23** [comment]
In config.yml
`# If the entity's spawns reason is listed below, do not stack.
reason-blacklist: [SPAWNER]
reason-blacklist-invert: true`

**Comment by SmexyDuk** [comment]
Thank you, it worked now.
