### ISSUE TITLE
StackMob is breaking mob cap.

### ISSUE THREAD

**Issue by benrobson** [Nathat23/StackMob-5#81]
The mob cap on multiplayer it's 70 for each player online.
When StackMob is installed it completely disregards this and spawns way too many, per player.

Running it on my server I have gotten reports from players that way too many mobs have been spawning than usual.

**Comment by Nathat23** [comment]
You can reduce the mob cap, so that players and have the same amount of mobs in a farm while the server ticks fewer entities.

**Comment by benrobson** [comment]
Where can I do that?

**Comment by Aurelien30000** [comment]
> Where can I do that?

bukkit.yml file, located in the main directory of your server ^^
