### ISSUE TITLE
[Request] Command to de-stack mobs

### ISSUE THREAD

**Issue by bluelhf** [Nathat23/StackMob-5#82]
The title says it all, it'd be lovely to have a command to de-stack a stacked mob, or all stacked mobs, for that matter.

**Comment by Nathat23** [comment]
You can destack mobs using the stacking tool, which can be acquired by using the command '/sm tool'

**Comment by bluelhf** [comment]
Hey, I'm aware of this, but to my knowledge slice just removes one entity from one stack. Would it be possible to simultaneously and completely unstack every entity?

**Comment by Nathat23** [comment]
If you shift-right-click the entity you can change the mode to either remove a single entity or all entities in a chunk.
