### ISSUE TITLE
Console error about PlayerShearEntityEvent Stackmob v5.1.1

### ISSUE THREAD

**Issue by Blatower21** [Nathat23/StackMob-5#85]
I'm getting this error in console that seems to be related when players shear sheeps.

`[22:40:11] [Server thread/ERROR]: Could not pass event PlayerShearEntityEvent to StackMob v5.1.1`
`java.lang.IllegalArgumentException: Stack size can not be less than one!`
`	at uk.antiperson.stackmob.entity.StackEntity.setSize(StackEntity.java:32) ~[?:?]`
`	at uk.antiperson.stackmob.entity.StackEntity.setSize(StackEntity.java:23) ~[?:?]`
`	at uk.antiperson.stackmob.entity.StackEntity.splitIfNotEnough(StackEntity.java:198) ~[?:?]`
`	at uk.antiperson.stackmob.listeners.ShearListener.shearLogic(ShearListener.java:76) ~[?:?]`
`	at uk.antiperson.stackmob.listeners.ShearListener.onShearSheep(ShearListener.java:36) ~[?:?]`
`	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor588.execute(Unknown Source) ~[?:?]`
`	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-245]`
`	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-245]`
`	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-245]`
`	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-245]`
`	at net.minecraft.server.v1_15_R1.EntitySheep.a(EntitySheep.java:152) ~[patched_1.15.2.jar:git-Paper-245]`
`	at net.minecraft.server.v1_15_R1.EntityInsentient.b(EntityInsentient.java:1079) ~[patched_1.15.2.jar:git-Paper-245]`
`	at net.minecraft.server.v1_15_R1.EntityHuman.a(EntityHuman.java:940) ~[patched_1.15.2.jar:git-Paper-245]`
`	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2065) ~[patched_1.15.2.jar:git-Paper-245]`
`	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.15.2.jar:git-Paper-245]`
`	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.15.2.jar:git-Paper-245]`
`	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-245]`
`	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-245]`
`	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-245]`
`	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-245]`
`	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-245]`
`	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081) ~[patched_1.15.2.jar:git-Paper-245]`
`	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074) ~[patched_1.15.2.jar:git-Paper-245]`
`	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-245]`
`	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1148) ~[patched_1.15.2.jar:git-Paper-245]`
`	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-245]`
`	at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by Nathat23** [comment]
From that error (and in my testing), this error is produced when an item has a negative durability. Is this the case?

**Comment by Blatower21** [comment]
I'm not sure about that, I only see the error in logs, can't replicate it

**Comment by Nathat23** [comment]
Well the only way I've found to produce this same error is to use the command:
`/minecraft:give @p minecraft:shears{Damage:239}`

**Comment by Blatower21** [comment]
That's true, I can reproduce it doing that, hum

**Comment by Nathat23** [comment]
@Blatower21 Any update on this?

**Comment by Blatower21** [comment]
Still happening

**Comment by Nathat23** [comment]
I believe this is the same as #143 which has been fixed.
