### ISSUE TITLE
can't use sm tool

### ISSUE THREAD

**Issue by mrcoffee1026** [Nathat23/StackMob-5#9]
the "stick" is in use by at least 3 different plugins so please be more specific with your tool.   For now I can't get anything except for land claim information (grief prevention) when right clicking or shift right clicking with the stack mob "stick".

**Comment by Nathat23** [comment]
I will change the material to a bone then, hopefully it won't interfere.

**Comment by Nathat23** [comment]
Fixed in above commit.

**Comment by mrcoffee1026** [comment]
kewl thanks!
