### ISSUE TITLE
Zombie Spawner Bug

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#90]
I have recently received the following report:
https://ecocitycraft.com/forum/threads/zombie-spawner-bug.198686/

We are using StackMob 5.1.2
Paper Build 282
StackMob config: https://pastebin.com/yMLU2dGE

**Comment by Nathat23** [comment]
In your provided config, the value 'traits.age' is disabled. This being disabled means that adult zombies can spawn in place of baby zombies, since both have different sizes they can get stuck in blocks.

**Comment by andrewkm** [comment]
Yes, this is an intended config change that I'd like to leave on. Is there anything I can do regarding the glitching in the report?

**Comment by andrewkm** [comment]
Any ideas @Nathat23
