### ISSUE TITLE
Panda stacking

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-5#91]
Can we have pandas with the genes able to not be stacked with others in different genes. Players want to have different pandas and they are stacking. Relates to https://minecraft.gamepedia.com/Panda#Genetics

**Comment by Nathat23** [comment]
So should stacking be based on the main gene or the hidden gene or both?

**Comment by LogGits** [comment]
I think both, because if you choose either it will prevent a portion of them from ever existing and therefore change mc behaviour.

**Comment by Nathat23** [comment]
Considering that there are 47 different combinations of genes, unless your players have panda farms with 1000s of pandas, would it would be more effective to just disable stacking for pandas completely?

**Comment by LogGits** [comment]
Fair point, I was thinking about aesthetics. There are no significant advantages to keeping large amounts of pandas so i just disabled panda stacking as u recommended 🙂
