### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by OFABLE** [Nathat23/StackMob-5#92]
I would like to make all mobs stack, and I started with a few of the basic ones. I tried getting the normal config to work but with no avail, so I tried messing with the config myself, tweaked a couple of the settings, and still, nothing. I get this error in console every time I try to spawn something:

[23:02:50] [Server thread/WARN]: [StackMob] Task #338 for StackMob v5.1.2 generated an exception
java.lang.UnsupportedOperationException: types-blacklist list is null!
at uk.antiperson.stackmob.config.ConfigList.contains(ConfigList.java:24) ~[?:?]
at uk.antiperson.stackmob.config.MainConfig.isEntityBlacklisted(MainConfig.java:167) ~[?:?]
at uk.antiperson.stackmob.listeners.SpawnListener.lambda$onSpawn$0(SpawnListener.java:25) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[Spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [Spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [Spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [Spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [Spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [Spigot-1.15.2.jar:git-Spigot-a03b1fd-5838285]
at java.lang.Thread.run(Thread.java:834) [?:?]

Then, here's my config:

# StackMob 5.0 Configuration file - by antiPerson and contributors.

# Most options can be customised for specific entity types, for details about this, see the end of this file.
# Asterisk meaning:
# (*) This option cannot be overridden in the 'custom' section at the end of this file.
# (**) The following option requires the use of Paper (https://papermc.io) because the API needed is not in Spigot.

stack:
  # The maximum size that a stack can have.
  max-size: 2000
  # How often entities should be checked for stacking (in ticks. 20 ticks = 1 second) (*)
  interval: 100
  # The area around an entity for which applicable stacks should be found.
  # Format: [(x cord),(y cord),(z cord)]
  merge-range: [17,17,17]
  # Only begin to stack entities when this amount of entities are nearby.
  threshold:
    enabled: true
    amount: 2

# Names of worlds where there should be no stacking
worlds-blacklist: []
worlds-blacklist-invert: false
# Types of entity which should not stack
types-blacklist: 
types-blacklist-invert: false
# If the entity's spawns reason is listed below, do not stack.
reason-blacklist: []
reason-blacklist-invert: false

display-name:
  # The formatting of the name tag which is shown when the stack size is above the threshold.
  # Placeholders:
  # %type% - the entity's type
  # %size% - the size of the stack
  format: '&a%type% &d(%size%)'
  # Whether the display tag can only be seen when the player targets the entity.
  # Mode:
  # ALWAYS - The tag will always be visible as long as the entity is loaded.
  # HOVER - The tag will only be visible when the player hovers their crosshair on the entity.
  # NEARBY - The tag will only be visible when the player is in range of the entity. (more resource intensive)
  visibility: HOVER
  # Options for when 'NEARBY' is used above. (*)
  nearby:
    # The range from which the tag should be visible.
    # Format: [(x cord),(y cord),(z cord)]
    range: [16,16,16]
    # How often (in ticks) the tag visibility status of an entity should be updated. (20 ticks = 1 second)
    interval: 20
  # Don't show the tag if the stack size of this entity if it is equal to or below the value specified.
  threshold: 1

# Whether entity specific traits (eg. profession, colour) should be segregated (*)
traits:
  sheep-color: false
  sheep-sheared: false
  slime-size: false
  horse-color: false
  llama-color: false
  parrot-variant: false
  drowned-hand-item: false
  age: false
  breed-mode: false
  love-mode: false
  cat-type: false
  mooshroom-variant: false
  fox-type: false
  bee-nectar: false
  bee-stung: false

# Prevent stacked mobs from targeting players.
# Similar to no-ai, but allows for movement of entities.
disable-targeting:
  enabled: true
  # If the entity's type is listed below, do not disable targeting.
  type-blacklist: []
  type-blacklist-invert: false
  # If the entity's spawns reason is listed below, do not disable targeting (**)
  reason-blacklist: []
  reason-blacklist-invert: false

# What should be done when these entity actions occur. (*)
events:
  # When an entity is feed its food.
  breed:
    enabled: true
    # MULTIPLY - spawn as many baby entities possible providing there is enough food fed.
    # SPLIT - slice off an entity to that it can be bred normally.
    mode: MULTIPLY
  # When an entity is dyed.
  dye:
    enabled: false
    # MULTIPLY - dye as many entities possible providing there is enough dye.
    # SPLIT - slice off an entity to that it can be dyed normally.
    mode: MULTIPLY
  # When an entity is sheared.
  shear:
    enabled: true
    # MULTIPLY - shear as many entities possible providing the shears have enough durability.
    # SPLIT - slice off an entity to that it can be sheared normally.
    mode: MULTIPLY
  multiply:
    # Chicken eggs and turtle scutes.
    drops: true
    explosion: true
    slime-split: true
  divide:
    nametag: true
    tame: true
  remove-stack-data:
    # Should we remove the stack data of an entity that was unstacked as a result of nametag division/split?
    # Setting this to false will cause entities that were nametagged to potentially become stacked again.
    nametag: true

# How entities should die
death:
  # Death options:
  # SINGLE - Only one entity dies.
  # ALL - Every entity dies.
  # STEP - A random amount dies.
  # STEP_DAMAGE - An amount that depends on the damage done dies.
  #
  # The priority 1 is highest and 4 is lowest.
  # If the killed entity is blacklisted, either by type or death reasons, by the highest priority method,
  # then it will attempt to use the next highest priority death method.
  SINGLE:
    priority: 4
    reason-blacklist: []
    reason-blacklist-invert: false
    type-blacklist: []
    type-blacklist-invert: false
  ALL:
    priority: 3
    reason-blacklist: []
    reason-blacklist-invert: false
    type-blacklist: []
    type-blacklist-invert: false
  STEP:
    priority: 2
    reason-blacklist: []
    reason-blacklist-invert: false
    type-blacklist: []
    type-blacklist-invert: false
    max-step: 5
    min-step: 1
  STEP_DAMAGE:
    priority: 1
    reason-blacklist: []
    reason-blacklist-invert: false
    type-blacklist: []
    type-blacklist-invert: false

# Multiply entity drops on entity death.
drops:
  enabled: true
  use-loot-tables: true
  # If each mob should only drop one of the items in the list.
  one-per-stack: []
  one-per-stack-invert: false
  # Items that should not be dropped.
  item-blacklist: []
  item-blacklist-invert: false
  # Death reasons that should not mean that drops are multiplied.
  reason-blacklist: []
  reason-blacklist-invert: false
  # Types of entity for which drops should not be dropped for.
  type-blacklist: []
  type-blacklist-invert: false

# Multiply entity experience on entity death.
experience:
  enabled: true
  # The bounds that should be used for the random multiplier.
  multiplier-min: 0.5
  multiplier-max: 0.8
  # Types of entity for which exp should not be dropped for.
  type-blacklist: []
  type-blacklist-invert: false

# Multiply the player stats which can be seen by the player from the game menu.
player-stats: true

# If specific entities should have a waiting time before their first stack.
# Designed for monster grinders etc.
wait-to-stack:
  enabled: false
  # For (x) times the stack task fires after spawn, don't stack this entity.
  wait-time: 0
  # Entity types that this should work for.
  types-whitelist:
    - ZOMBIE
    - SKELETON
    - PIG_ZOMBIE
    - CREEPER
    - ENDERMAN
    - IRON_GOLEM
    - ENDERMAN
    - CREEPER
    - BLAZE
    - PIG_ZOMBIE
    - VILLAGER
    - COW
    - CHICKEN
    - SHEEP
  types-whitelist-invert: false
  # Spawn reasons that this should work for.
  reasons-whitelist:
    - SPAWNER
    - NATURAL
    - EGG
  reasons-whitelist-invert: false

# Enable/disable integration with other plugins. (*)
hooks:
  # Allows the custom 'entity-stacking' flag to be used in worldguard regions.
  worldguard: true
  mythicmobs:
    enabled: true
    blacklist: []
    blacklist-invert: false
  # Prevent citizens npcs from stacking.
  citizens: true
  # Prevent stacked entities from giving mcmmo experience.
  mcmmo: true
  # Prevent stacked entities from giving job payments.
  jobs: true

## Some options can be modified for specific entity types. An example is shown below. Remove comments to see this in action.
  CREEPER:
    stack:
      max-size: 2000
  SKELETON:
    stack:
      max-size: 2000      
  ZOMBIE:
    stack:
      max-size: 2000  
  PIG_ZOMBIE:
    stack:
      max-size: 2000     
  COW:
    stack:
      max-size: 2000
  SHEEP:
    stack:
      max-size: 2000
  CHICKEN:
    stack:
      max-size: 2000
  SPIDER:
    stack:
      max-size: 2000
  ENDERMAN:
    stack:
      max-size: 2000
  BLAZE:
    stack:
      max-size: 2000
  VILLAGER:
    stack:
      max-size: 2000

**Comment by OFABLE** [comment]
Just to add, I've tried spawning with spawners/egg, nothing yielded any results.

**Comment by Nathat23** [comment]
'types-blacklist' needs to have '[]' as its value, it cannot be blank.
