### ISSUE TITLE
Bee Stacking

### ISSUE THREAD

**Issue by 3576s** [Nathat23/StackMob-5#93]
I can't figure out why bees are still stacking! I'm new to this and require help, it's just for a SMP server.

(removed because its spammy, see below)

**Comment by Aurelien30000** [comment]
Please provide your config parsed or through pastebin, it's unreadable :c 
_I think you forgot the comma "," between VILLAGER and BEE._

**Comment by 3576s** [comment]
https://pastebin.com/GFVfcqhM

**Comment by Aurelien30000** [comment]
I confirm my last supposition ^^ A list is formed like that "[VILLAGER, BEE]"
