### ISSUE TITLE
Lead issues

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-5#95]
Having a few issues with leads.

1) Lead a stacked sheep (for example) and connect the lead to a fence. Once you start breeding the stack, the split sheep stays tied up but the stack gets taken off the lead. This makes it annoying to players setting up complex farm designs.

2) If you have a leashed sheep stack and another leashed sheep stack, the two will combine without dropping the lead.

**Comment by Nathat23** [comment]
So regarding your first point, do you want the split sheep to also be attached to the same leash?

**Comment by LogGits** [comment]
The stack should remain attached with the split ones being detached

**Comment by Nathat23** [comment]
This has been fixed in the above commit.
