### ISSUE TITLE
Bunch of Console errors

### ISSUE THREAD

**Issue by itzWebby1** [Nathat23/StackMob-5#96]
"wait-to-stack.reasons-whitelist list is null"

The reasons-whitelist is empty but I'm not sure what to put in there.

**Comment by itzWebby1** [comment]
Task #26727 for StackMob v5.1.2 generated an exception
25.05 22:40:04 [Server] INFO java.lang.UnsupportedOperationException: wait-to-stack.reasons-whitelist list is null!
25.05 22:40:04 [Server] INFO at uk.antiperson.stackmob.config.ConfigList.contains(ConfigList.java:24) ~[?:?]
25.05 22:40:04 [Server] INFO at uk.antiperson.stackmob.entity.StackEntity.shouldWait(StackEntity.java:58) ~[?:?]
25.05 22:40:04 [Server] INFO at uk.antiperson.stackmob.listeners.SpawnListener.lambda$onSpawn$0(SpawnListener.java:32) ~[?:?]
25.05 22:40:04 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-"de5b093"]
25.05 22:40:04 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-"de5b093"]
25.05 22:40:04 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-"de5b093"]
25.05 22:40:04 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-"de5b093"]
25.05 22:40:04 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-"de5b093"]
25.05 22:40:04 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-"de5b093"]

**Comment by Nathat23** [comment]
you need to put [] on the end of the line.
