### ISSUE TITLE
[Question] API

### ISSUE THREAD

**Issue by EvilTerabite** [Nathat23/StackMob-5#98]
Hey! Where can I find a maven API for StackMobs?

**Comment by Aurelien30000** [comment]
There is no maven API, you must import it through the jar, like that :

> <dependency>
    <dependency>
        <groupId>uk.antiperson.stackmob</groupId>
        <artifactId>stackmob</artifactId>
        <version>5.1.2</version>
        <scope>system</scope>
        <systemPath>${project.basedir}/jars/StackMob.jar</systemPath> 
    </dependency>

Ps : Maybe we could use Github actions and packages 🤔 @Nathat23
